### Linear regression model V15
try random forest regressor

In [2]:
fileprefix='./lateness_PREP_V10_'

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [5]:
df_X.shape

(125675, 215)

In [6]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [7]:
type(df_y)
df_y.shape

(125675, 2)

In [8]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [9]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [10]:
y.shape

(125675,)

In [11]:
df_X.head()

Unnamed: 0  lead_organizer_created_at_pdt_hour  creator_id  \
0           5                                  19       81281   
1           6                                  19       80068   
2           7                                  20       87802   
3           8                                  20       81561   
4           9                                  19       76793   

   claimed_at_pdt_hour_14  origin_region_name_East Bay South  \
0                       0                                  0   
1                       0                                  0   
2                       0                                  0   
3                       0                                  0   
4                       0                                  0   

   scheduled_starts_at_pdt_month  carpool_int  \
0                              2            0   
1                              1            0   
2                              2            0   
3                              1            0   
4                              1            0   

   scheduled_starts_at_pdt_weekofyear  scheduled_starts_at_pdt_hour_2  \
0                                   7                               0   
1                                   4                               0   
2                                   6                               0   
3                                   4                               0   
4                                   4                               0   

   origin_region_name_Central LA - West    ...      destination_region_id  \
0                                     0    ...                       36.0   
1                                     0    ...                       36.0   
2                                     0    ...                       48.0   
3                                     0    ...                       36.0   
4                                     0    ...                       33.0   

   claimed_at_pdt_hour_6  organizers_count  scheduled_starts_at_pdt_hour_5  \
0                      0               1.0                               0   
1                      0               1.0                               0   
2                      0               1.0                               0   
3                      0               1.0                               0   
4                      0               1.0                               0   

   scheduled_starts_at_pdt_hour_6  origin_region_name_Ventura  \
0                               0                           0   
1                               0                           0   
2                               0                           0   
3                               0                           0   
4                               0                           0   

   lead_organizer_created_at_pdt_month  scheduled_starts_at_pdt_month_2  \
0                                    7                                1   
1                                    7                                0   
2                                    7                                1   
3                                    7                                0   
4                                    7                                0   

   origin_region_name_Pomona Valley  driver_id  
0                                 0    62969.0  
1                                 0    62969.0  
2                                 0    62969.0  
3                                 0    62969.0  
4                                 0    62969.0  

[5 rows x 215 columns]

In [12]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [13]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [14]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 215)
(25135, 215)
(100540,)
(25135,)


In [16]:
# select a regressor
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(max_depth=2, random_state=808, n_estimators=100)

In [17]:
# fit model
model=model.fit(X_train,y_train)

In [19]:
print(model.feature_importances_)

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.04130382 0.         0.
 0.         0.         0.         0.         0.         

In [41]:
importances = list(zip(model.feature_importances_, X_train.columns))
importances.sort(reverse=True)
importances

[(0.5090825367034921, 'scheduled_starts_at_pdt_hour'),
 (0.19822274976683996, 'scheduled_ends_at_pdt_hour'),
 (0.19602317363507468, 'claimed_before_trip_start_secs'),
 (0.041303821019345134, 'driver_previous_completed_trips'),
 (0.03370704837612013, 'driver_signup_before_trip_start_secs'),
 (0.01228084868966317, 'driver_signup_before_trip_claimed_secs'),
 (0.006976899715188964, 'driver_created_at_pdt_dayofyear'),
 (0.002402922094275764, 'driver_id'),
 (0.0, 'trip_template_id'),
 (0.0, 'trip_predicted_raw_fare'),
 (0.0, 'trip_est_duration_secs'),
 (0.0, 'trip_created_before_trip_start_secs'),
 (0.0, 'trip_claimed_after_trip_created'),
 (0.0, 'total_predicted_duration'),
 (0.0, 'total_predicted_distance_miles'),
 (0.0, 'shuttle_int'),
 (0.0, 'scheduled_starts_at_pdt_weekofyear'),
 (0.0, 'scheduled_starts_at_pdt_weekday_6'),
 (0.0, 'scheduled_starts_at_pdt_weekday_5'),
 (0.0, 'scheduled_starts_at_pdt_weekday_4'),
 (0.0, 'scheduled_starts_at_pdt_weekday_3'),
 (0.0, 'scheduled_starts_at_pdt

In [20]:
#model.coef_

In [21]:
#pd.Series(model.coef_).astype(int)

In [22]:
#model.intercept_

In [23]:
#X_train.std()

In [24]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
# use print to see every feature not just first 20 and last 20
#print((model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int).to_string())

In [25]:
# score against TRAINING set
model.score(X_train,y_train)

0.04030694358867759

In [26]:
# score against TEST set
model.score(X_test,y_test)

0.04146379108598386

In [27]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [28]:
type(model_y_test_pred)

numpy.ndarray

In [29]:
model_y_test_pred[:10]

array([-477.01780649, -467.94496036, -467.94496036, -467.94496036,
       -475.62903594, -467.94496036, -263.67184248, -467.94496036,
       -467.94496036, -467.94496036])

In [30]:
pd.Series(model_y_test_pred).std()

91.15745188847566

In [31]:
pd.Series(model_y_test_pred).corr(y_test)

-0.03208018533102128

In [32]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.041 8.36 251546 0.041 376 286 4.76


In [33]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [34]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [35]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [36]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25069]
 [    1    14]
 [    2    52]]


In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.29      0.00      0.00      2939
          2       0.27      0.02      0.03       892
          3       0.00      0.00      0.00       148

avg / total       0.75      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [38]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21144     3     9     0]
 [ 2921     4    14     0]
 [  874     4    14     0]
 [  130     3    15     0]]
