# Linear regression model V3
normalize features

In [1]:
fileprefix='./lateness_PREP_V1_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 29)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
y=df_y.iloc[:,1]

In [8]:
type(y)

pandas.core.series.Series

In [9]:
y.shape

(125675,)

In [10]:
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [11]:
df_X.head()

Unnamed: 0  total_predicted_distance_miles  \
0           5                            10.0   
1           6                             5.0   
2           7                             5.0   
3           8                             7.0   
4           9                            13.0   

   lead_organizer_previous_completed_trips  total_predicted_duration  \
0                                        5                     36.47   
1                                       65                     29.00   
2                                       13                     18.90   
3                                       88                     22.93   
4                                       46                     35.50   

   predicted_driver_fare  organizer_home_lat  destination_lat  \
0                  19.63               34.17            34.18   
1                  14.19               34.08            34.10   
2                  14.06               34.16            34.16   
3                  15.59               34.05            34.17   
4                  21.63               34.12            34.12   

   driver_previous_completed_trips  destination_region_id  coupon_consumed  \
0                            663.0                   36.0              0.0   
1                            634.0                   36.0              0.0   
2                            649.0                   48.0              0.0   
3                            637.0                   36.0              0.0   
4                            629.0                   33.0              0.0   

         ...         driver_home_lon  passengers_count  origin_lon  \
0        ...                 -118.25               1.0     -118.35   
1        ...                 -118.25               1.0     -118.31   
2        ...                 -118.25               1.0     -118.16   
3        ...                 -118.25               1.0     -118.24   
4        ...                 -118.25               1.0     -118.51   

   organizer_home_lon  trip_template_id  origin_lat  claimed_after_created  \
0             -118.34               0.0       34.18                2753.65   
1             -118.34            6325.0       34.10                5867.40   
2             -118.11               0.0       34.13                  32.20   
3             -118.22               0.0       34.11                  22.28   
4             -118.38            3719.0       34.20              150534.13   

   destination_lon  driver_home_lat  route_legs_count  
0          -118.23             34.1                 1  
1          -118.24             34.1                 1  
2          -118.11             34.1                 1  
3          -118.28             34.1                 1  
4          -118.38             34.1                 1  

[5 rows x 29 columns]

In [12]:
y.describe().round()

count     125675.0
mean        -507.0
std        22763.0
min     -7862491.0
25%         -657.0
50%         -324.0
75%          -96.0
max       204537.0
Name: 1, dtype: float64

In [13]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [14]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 29)
(25135, 29)
(100540,)
(25135,)


In [15]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [16]:
# fit model
model=model.fit(X_train,y_train)

In [17]:
model.coef_

array([-1.80606026e-04,  5.64019193e+01,  3.90589863e-02,  3.01982676e+01,
       -4.09241064e+01, -5.75490534e+02, -2.12228665e+04,  1.33749491e+00,
        4.99173756e+01, -5.28967860e+02, -3.83978900e-03, -8.15103539e-03,
        4.90276755e-03,  1.90555142e+02,  1.49533665e-03,  2.31390407e-03,
        5.20806921e+01,  1.84881423e-03, -5.10748707e+00, -9.70440480e+03,
        7.11507272e+01,  5.58466314e+03, -1.69883926e+02, -1.67327913e-02,
       -2.81867787e+04, -3.30540602e-03,  3.52346514e+03,  5.01274949e+04,
       -3.83638232e+02])

In [35]:
pd.Series(model.coef_).astype(int)

0         0
1        56
2         0
3        30
4       -40
5      -575
6    -21222
7         1
8        49
9      -528
10        0
11        0
12        0
13      190
14        0
15        0
16       52
17        0
18       -5
19    -9704
20       71
21     5584
22     -169
23        0
24   -28186
25        0
26     3523
27    50127
28     -383
dtype: int64

In [19]:
model.intercept_

-98904.2533150271

In [20]:
df_X.std()

Unnamed: 0                                 62574.764615
total_predicted_distance_miles                 5.648633
lead_organizer_previous_completed_trips      205.035384
total_predicted_duration                      12.495387
predicted_driver_fare                          5.869914
organizer_home_lat                             3.520902
destination_lat                                1.465935
driver_previous_completed_trips              343.170859
destination_region_id                         14.230953
coupon_consumed                                0.078336
id                                         90386.207317
creator_id                                 28361.473481
driver_id                                  36476.929023
organizers_count                               0.172448
destination_location_id                    36903.795020
origin_location_id                         36848.424811
origin_region_id                              14.245880
lead_organizer_id                          28366

In [36]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/df_X.std()).sort_values(axis=0).astype(int)

origin_lat                                -19228
destination_lat                           -14477
coupon_consumed                            -6752
driver_home_lon                            -5753
route_legs_count                           -1377
organizer_home_lat                          -163
organizer_home_lon                           -15
predicted_driver_fare                         -6
trip_predicted_raw_fare                        0
trip_template_id                               0
creator_id                                     0
claimed_after_created                          0
id                                             0
Unnamed: 0                                     0
destination_location_id                        0
origin_location_id                             0
lead_organizer_id                              0
driver_id                                      0
lead_organizer_previous_completed_trips        0
driver_previous_completed_trips                0
total_predicted_dura

In [22]:
# score against TEST set
model.score(X_test,y_test)

-67.96033800845635

In [23]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([ 9993.71028529,   177.10088028,  1438.91834706, -2715.98537305,
       -3960.78922074,  -632.19060602, -1986.1043895 ,  4843.24000458,
       -2814.57160266, -5068.66299951])

In [26]:
pd.Series(model_y_test_pred).std()

11885.066992753233

In [27]:
pd.Series(model_y_test_pred).corr(y_test)

0.006368537153212968

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
print ("%.3f %.0f %.3f %.0f %.0f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred)))

-67.956 143688765 -67.960 3405 2119


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 14171]
 [    1   936]
 [    2  1811]
 [    3  8217]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.56      0.67     21156
          1       0.13      0.04      0.06      2939
          2       0.02      0.05      0.03       892
          3       0.01      0.35      0.01       148

avg / total       0.72      0.48      0.57     25135



In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[11845   779  1543  6989]
 [ 1698   122   211   908]
 [  546    33    45   268]
 [   82     2    12    52]]
