### Linear regression model V5
with 10 duration features added in seconds

In [1]:
fileprefix='./lateness_PREP_V3_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 45)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
y=df_y.iloc[:,1]

In [8]:
type(y)

pandas.core.series.Series

In [9]:
y.shape

(125675,)

In [10]:
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [11]:
df_X.head()

Unnamed: 0  org_signup_before_trip_created_secs  passengers_count  \
0           5                           18754828.0               1.0   
1           6                           16683716.0               1.0   
2           7                           18750712.0               1.0   
3           8                           17785068.0               1.0   
4           9                            7921943.0               1.0   

   destination_lon  coupon_consumed  lead_organizer_previous_completed_trips  \
0          -118.23              0.0                                        5   
1          -118.24              0.0                                       65   
2          -118.11              0.0                                       13   
3          -118.28              0.0                                       88   
4          -118.38              0.0                                       46   

   driver_signup_before_trip_created_secs  origin_region_id  creator_id  \
0                              18685416.0              44.0       81281   
1                              16613901.0              33.0       80068   
2                              18684204.0              48.0       87802   
3                              17715744.0              36.0       81561   
4                               7851048.0              45.0       76793   

   total_predicted_duration           ...             is_repeating_ride_int  \
0                     36.47           ...                                 0   
1                     29.00           ...                                 1   
2                     18.90           ...                                 0   
3                     22.93           ...                                 0   
4                     35.50           ...                                 1   

   driver_signup_before_trip_start_secs  destination_location_id  \
0                            19442622.0                  86289.0   
1                            17629422.0                  86075.0   
2                            18924222.0                  88361.0   
3                            17802822.0                  87908.0   
4                            17537322.0                  89633.0   

   route_legs_count  driver_id  origin_lat  organizers_count  \
0                 1    62969.0       34.18               1.0   
1                 1    62969.0       34.10               1.0   
2                 1    62969.0       34.13               1.0   
3                 1    62969.0       34.11               1.0   
4                 1    62969.0       34.20               1.0   

   organizer_home_lat  origin_lon  trip_predicted_raw_fare  
0               34.17     -118.35                    32.50  
1               34.08     -118.31                    23.09  
2               34.16     -118.16                    17.81  
3               34.05     -118.24                    22.56  
4               34.12     -118.51                    36.19  

[5 rows x 45 columns]

In [12]:
y.describe().round()

count     125675.0
mean        -507.0
std        22763.0
min     -7862491.0
25%         -657.0
50%         -324.0
75%          -96.0
max       204537.0
Name: 1, dtype: float64

In [13]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [14]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 45)
(25135, 45)
(100540,)
(25135,)


In [15]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [16]:
# fit model
model=model.fit(X_train,y_train)

In [17]:
model.coef_

array([-4.46304923e-04,  2.83062873e+07,  1.58809831e+01,  7.63070636e+01,
        4.26297518e+00,  1.41224972e-01, -4.19374691e+07,  3.97251150e-01,
       -4.74131379e-03,  7.98521358e+03, -3.32454183e+01, -4.16779938e+01,
        2.13585671e+00, -7.70422994e-02, -1.60591932e+01, -4.56784399e-04,
       -1.33112258e+02,  1.96415907e-03, -2.80847512e+07,  2.59900338e+07,
        8.29713028e+00,  1.03576627e+07,  1.56323711e+07,  5.92842852e+01,
        9.66202213e-03,  4.03756802e-01, -1.46301573e+02, -1.98884083e-04,
        1.11771517e+01, -1.49192226e+01, -3.27351899e+06, -3.47065909e+01,
        2.21536152e+05,  1.41574844e+02, -2.05373933e+02,  7.31242463e+01,
        1.57258991e+07,  3.76191224e-04, -2.16417343e+02,  3.16118237e-03,
        5.32997191e+02,  7.34760994e+01, -5.10912076e+01,  1.45764811e+02,
       -5.81321772e+00])

In [18]:
pd.Series(model.coef_).astype(int)

0            0
1     28306287
2           15
3           76
4            4
5            0
6    -41937469
7            0
8            0
9         7985
10         -33
11         -41
12           2
13           0
14         -16
15           0
16        -133
17           0
18   -28084751
19    25990033
20           8
21    10357662
22    15632371
23          59
24           0
25           0
26        -146
27           0
28          11
29         -14
30    -3273518
31         -34
32      221536
33         141
34        -205
35          73
36    15725899
37           0
38        -216
39           0
40         532
41          73
42         -51
43         145
44          -5
dtype: int64

In [19]:
model.intercept_

12308.071845378414

In [20]:
X_train.std()

Unnamed: 0                                 6.259357e+04
org_signup_before_trip_created_secs        1.294888e+07
passengers_count                           5.874265e-01
destination_lon                            1.570260e+00
coupon_consumed                            7.915962e-02
lead_organizer_previous_completed_trips    2.078520e+02
driver_signup_before_trip_created_secs     1.246842e+07
origin_region_id                           1.424262e+01
creator_id                                 2.835762e+04
total_predicted_duration                   1.252958e+01
driver_home_lon                            1.696783e+00
destination_lat                            1.466265e+00
destination_region_id                      1.422844e+01
claimed_after_created                      3.024465e+04
shuttle_int                                9.784898e-02
origin_location_id                         3.680007e+04
trip_est_duration_secs                     7.517752e+02
lead_organizer_id                          2.836

In [21]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).astype(int)

is_same_day_ride_int                      -919
route_legs_count                          -773
shuttle_int                               -164
driver_home_lat                           -139
is_affiliate_int                          -129
destination_lat                            -28
driver_home_lon                            -19
organizer_home_lat                         -14
driver_signup_before_trip_created_secs      -3
org_signup_before_trip_start_secs           -2
trip_created_before_trip_start_secs         -1
organizer_home_lon                          -1
trip_predicted_raw_fare                      0
trip_est_duration_secs                       0
claimed_after_created                        0
creator_id                                   0
origin_location_id                           0
Unnamed: 0                                   0
id                                           0
destination_location_id                      0
lead_organizer_id                            0
driver_id    

In [22]:
# score against TRAINING set
model.score(X_train,y_train)

0.9500275931381763

In [23]:
# score against TEST set
model.score(X_test,y_test)

-0.023181727248209546

In [24]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [25]:
type(model_y_test_pred)

numpy.ndarray

In [26]:
model_y_test_pred[:10]

array([-108.23366245, -744.7595553 , -757.25321174, -441.9184738 ,
       -193.87206954, -476.65725213, -931.04175451, -124.31141246,
       -715.06430852, -270.610252  ])

In [27]:
pd.Series(model_y_test_pred).std()

242.2700100488003

In [28]:
pd.Series(model_y_test_pred).corr(y_test)

0.020457688191864953

In [29]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
print ("%.3f %.0f %.3f %.0f %.0f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred)))

-0.023 2131946 -0.023 447 332


In [30]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [31]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [32]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [33]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 24598]
 [    1   518]
 [    2    18]
 [    3     1]]


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.98      0.91     21156
          1       0.14      0.03      0.04      2939
          2       0.06      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.73      0.83      0.77     25135



In [35]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[20731   413    12     0]
 [ 2862    75     2     0]
 [  869    21     1     1]
 [  136     9     3     0]]
