# Linear regression model V4
with boolean features added as 1,0 features

In [1]:
fileprefix='./lateness_PREP_V2_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 35)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
y=df_y.iloc[:,1]

In [8]:
type(y)

pandas.core.series.Series

In [9]:
y.shape

(125675,)

In [10]:
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [11]:
df_X.head()

Unnamed: 0  origin_lon  total_predicted_distance_miles  \
0           5     -118.35                            10.0   
1           6     -118.31                             5.0   
2           7     -118.16                             5.0   
3           8     -118.24                             7.0   
4           9     -118.51                            13.0   

   destination_location_id  destination_lon  trip_predicted_raw_fare  \
0                  86289.0          -118.23                    32.50   
1                  86075.0          -118.24                    23.09   
2                  88361.0          -118.11                    17.81   
3                  87908.0          -118.28                    22.56   
4                  89633.0          -118.38                    36.19   

   coupon_consumed  lead_organizer_id  organizer_home_lon  \
0              0.0              81281             -118.34   
1              0.0              80068             -118.34   
2              0.0              87802             -118.11   
3              0.0              81561             -118.22   
4              0.0              76793             -118.38   

   is_same_day_ride_int       ...         trip_template_id  \
0                     0       ...                      0.0   
1                     0       ...                   6325.0   
2                     0       ...                      0.0   
3                     0       ...                      0.0   
4                     0       ...                   3719.0   

   is_repeating_ride_int  passengers_count  origin_location_id  \
0                      0               1.0             82879.0   
1                      1               1.0             83958.0   
2                      0               1.0             84580.0   
3                      0               1.0             87880.0   
4                      1               1.0             92149.0   

   destination_region_id  claimed_after_created  predicted_driver_fare  \
0                   36.0                2753.65                  19.63   
1                   36.0                5867.40                  14.19   
2                   48.0                  32.20                  14.06   
3                   36.0                  22.28                  15.59   
4                   33.0              150534.13                  21.63   

   route_legs_count  is_affiliate_int  driver_home_lon  
0                 1                 0          -118.25  
1                 1                 0          -118.25  
2                 1                 0          -118.25  
3                 1                 0          -118.25  
4                 1                 0          -118.25  

[5 rows x 35 columns]

In [12]:
y.describe().round()

count     125675.0
mean        -507.0
std        22763.0
min     -7862491.0
25%         -657.0
50%         -324.0
75%          -96.0
max       204537.0
Name: 1, dtype: float64

In [13]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [14]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 35)
(25135, 35)
(100540,)
(25135,)


In [15]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [16]:
# fit model
model=model.fit(X_train,y_train)

In [17]:
model.coef_

array([-1.92853056e-04,  5.60449749e+03,  5.19930315e+01,  1.18247045e-03,
        3.51637061e+03, -4.88539419e+00, -5.87425549e+02,  1.32490779e-02,
       -1.67418706e+02,  2.76737818e+02, -5.78342267e+02, -5.68419078e+02,
       -4.27814569e+02,  5.01237137e+04,  1.37883365e+00, -2.12056273e+04,
       -1.93155974e-02,  5.04949220e-03, -2.82082320e+04,  5.13887053e+01,
        2.84639807e+01, -6.09901329e-03, -1.08192065e+02, -7.70802732e-02,
        1.02218438e+03,  1.53897693e-01, -2.21508548e+03,  5.77931450e+01,
        2.00687599e-03,  4.98134332e+01,  1.47025564e-03, -3.62342540e+01,
       -3.86716177e+02,  1.29896669e+02, -9.70647566e+03])

In [18]:
pd.Series(model.coef_).astype(int)

0         0
1      5604
2        51
3         0
4      3516
5        -4
6      -587
7         0
8      -167
9       276
10     -578
11     -568
12     -427
13    50123
14        1
15   -21205
16        0
17        0
18   -28208
19       51
20       28
21        0
22     -108
23        0
24     1022
25        0
26    -2215
27       57
28        0
29       49
30        0
31      -36
32     -386
33      129
34    -9706
dtype: int64

In [19]:
model.intercept_

-95388.57623206552

In [35]:
X_train.std()

Unnamed: 0                                 62593.572542
origin_lon                                     1.569941
total_predicted_distance_miles                 5.668047
destination_location_id                    36887.288829
destination_lon                                1.570260
trip_predicted_raw_fare                       12.222037
coupon_consumed                                0.079160
lead_organizer_id                          28362.539772
organizer_home_lon                            11.007659
is_same_day_ride_int                           0.159046
organizers_count                               0.171734
organizer_home_lat                             3.493593
shuttle_int                                    0.097849
driver_home_lat                                1.476480
driver_previous_completed_trips              342.782841
destination_lat                                1.466265
creator_id                                 28357.616687
driver_id                                  36466

In [36]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).astype(int)

origin_lat                                -19239
destination_lat                           -14462
coupon_consumed                            -7420
driver_home_lon                            -5720
is_repeating_ride_int                      -4652
shuttle_int                                -4372
organizers_count                           -3367
route_legs_count                           -1382
driver_has_driven_this_route_before_int     -218
organizer_home_lat                          -162
organizer_home_lon                           -15
predicted_driver_fare                         -6
trip_predicted_raw_fare                        0
lead_organizer_previous_completed_trips        0
creator_id                                     0
id                                             0
Unnamed: 0                                     0
destination_location_id                        0
claimed_after_created                          0
origin_location_id                             0
driver_id           

In [39]:
# score against TRAINING set
model.score(X_train,y_train)

0.3722831322811122

In [37]:
# score against TEST set
model.score(X_test,y_test)

-67.98918692556897

In [38]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([10604.68937238,   258.42825308,  1772.90953286, -2379.00008807,
       -4136.27010871, -1141.00160023, -1812.67614023,  5022.49716351,
       -2634.94609103, -4762.80274687])

In [26]:
pd.Series(model_y_test_pred).std()

11887.618863407686

In [40]:
pd.Series(model_y_test_pred).corr(y_test)

0.006848441557800376

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
print ("%.3f %.0f %.3f %.0f %.0f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred)))

-67.985 143748875 -67.989 3413 2122


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 14160]
 [    1   944]
 [    2  1792]
 [    3  8239]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.56      0.67     21156
          1       0.12      0.04      0.06      2939
          2       0.03      0.05      0.04       892
          3       0.01      0.37      0.01       148

avg / total       0.72      0.48      0.57     25135



In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[11828   798  1517  7013]
 [ 1702   116   219   902]
 [  548    27    48   269]
 [   82     3     8    55]]
