### Linear regression model V14
try stochastic gradiant descent regressor

In [1]:
fileprefix='./lateness_PREP_V10_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 215)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  lead_organizer_created_at_pdt_hour  creator_id  \
0           5                                  19       81281   
1           6                                  19       80068   
2           7                                  20       87802   
3           8                                  20       81561   
4           9                                  19       76793   

   claimed_at_pdt_hour_14  origin_region_name_East Bay South  \
0                       0                                  0   
1                       0                                  0   
2                       0                                  0   
3                       0                                  0   
4                       0                                  0   

   scheduled_starts_at_pdt_month  carpool_int  \
0                              2            0   
1                              1            0   
2                              2            0   
3                              1            0   
4                              1            0   

   scheduled_starts_at_pdt_weekofyear  scheduled_starts_at_pdt_hour_2  \
0                                   7                               0   
1                                   4                               0   
2                                   6                               0   
3                                   4                               0   
4                                   4                               0   

   origin_region_name_Central LA - West    ...      destination_region_id  \
0                                     0    ...                       36.0   
1                                     0    ...                       36.0   
2                                     0    ...                       48.0   
3                                     0    ...                       36.0   
4                                     0    ...                       33.0   

   claimed_at_pdt_hour_6  organizers_count  scheduled_starts_at_pdt_hour_5  \
0                      0               1.0                               0   
1                      0               1.0                               0   
2                      0               1.0                               0   
3                      0               1.0                               0   
4                      0               1.0                               0   

   scheduled_starts_at_pdt_hour_6  origin_region_name_Ventura  \
0                               0                           0   
1                               0                           0   
2                               0                           0   
3                               0                           0   
4                               0                           0   

   lead_organizer_created_at_pdt_month  scheduled_starts_at_pdt_month_2  \
0                                    7                                1   
1                                    7                                0   
2                                    7                                1   
3                                    7                                0   
4                                    7                                0   

   origin_region_name_Pomona Valley  driver_id  
0                                 0    62969.0  
1                                 0    62969.0  
2                                 0    62969.0  
3                                 0    62969.0  
4                                 0    62969.0  

[5 rows x 215 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 215)
(25135, 215)
(100540,)
(25135,)


In [56]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.SGDRegressor(max_iter=10000)

In [57]:
# fit model
model=model.fit(X_train,y_train)

In [58]:
model.coef_

array([-2.15150791e+15,  9.41621960e+11,  8.56439469e+14,  1.99939501e+11,
        2.77887892e+10,  2.26135097e+11, -1.93672687e+10,  7.52468956e+10,
        0.00000000e+00,  1.16336469e+11,  1.68301155e+11, -2.17425334e+11,
        7.01858163e+10, -2.18114403e+10, -6.44488351e+12, -6.88961728e+11,
       -1.86160341e+11,  4.30277100e+10,  1.58025416e+09,  1.20657801e+11,
       -1.50840771e+12, -2.14466614e+11, -1.60513985e+12, -1.39650575e+11,
       -4.61591566e+11, -4.45595124e+10, -1.14804308e+11, -4.33523204e+12,
       -1.45002027e+11,  3.36710175e+11,  1.55456023e+09,  4.32560697e+10,
       -3.88998349e+10, -3.83727047e+10, -4.71501475e+10, -3.20633126e+12,
       -1.43079712e+10, -1.20878804e+11, -1.45354391e+11,  1.78170928e+10,
        2.26973597e+11,  2.68984238e+10,  6.57626301e+10,  7.52468956e+10,
        1.96493213e+15, -1.86078017e+15,  2.10225700e+11, -3.30314162e+11,
        2.85410299e+11,  1.16201018e+11, -6.89142587e+11,  1.82485123e+10,
        5.11094159e+10,  

In [59]:
pd.Series(model.coef_).astype(int)

0     -2151507910260358
1          941621959763
2       856439469294688
3          199939500798
4           27788789233
5          226135097044
6          -19367268653
7           75246895605
8                     0
9          116336469283
10         168301155362
11        -217425334284
12          70185816257
13         -21811440305
14       -6444883513345
15        -688961727875
16        -186160341040
17          43027709990
18           1580254164
19         120657801394
20       -1508407710877
21        -214466614201
22       -1605139847597
23        -139650575415
24        -461591566445
25         -44559512395
26        -114804307906
27       -4335232040674
28        -145002026910
29         336710175078
             ...       
185         44543466585
186        -87892219466
187         42339924438
188        -17051405239
189       1434963300979
190       -165351119588
191          -123951680
192         -3602425046
193         -7604173228
194        -14683957737
195         4922

In [60]:
model.intercept_

array([2.43695701e+11])

In [61]:
X_train.std()

Unnamed: 0                               6.259357e+04
lead_organizer_created_at_pdt_hour       4.782270e+00
creator_id                               2.835762e+04
claimed_at_pdt_hour_14                   2.110560e-01
origin_region_name_East Bay South        1.291162e-01
scheduled_starts_at_pdt_month            3.471655e+00
carpool_int                              1.312920e-01
scheduled_starts_at_pdt_weekofyear       1.507374e+01
scheduled_starts_at_pdt_hour_2           0.000000e+00
origin_region_name_Central LA - West     2.467008e-01
claimed_at_pdt_weekday_5                 2.344145e-01
lead_organizer_created_at_pdt_quarter    8.076552e-01
claimed_at_pdt_month_3                   2.793281e-01
claimed_at_pdt_hour_8                    2.012094e-01
total_predicted_duration                 1.252958e+01
scheduled_starts_at_pdt_weekday          1.357037e+00
claimed_at_pdt_month_10                  3.337243e-01
lead_organizer_platform_web              7.853678e-02
is_same_day_ride_int        

In [62]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
# use print to see every feature not just first 20 and last 20
print((model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int).to_string())

claimed_at_pdt_hour_1                             -1463574705014
origin_region_name_San Francisco                  -1245737062248
scheduled_starts_at_pdt_hour_21                   -1146182897897
origin_region_name_San Jose                       -1132395076164
origin_region_name_Westside                        -944598412791
claimed_at_pdt_weekday_3                           -916582016790
predicted_driver_fare                              -877058054702
claimed_at_pdt_hour_17                             -870289046005
scheduled_ends_at_pdt_day                          -838301049736
scheduled_starts_at_pdt_day                        -838280665294
scheduled_starts_at_pdt_hour_4                     -834436979267
claimed_at_pdt_hour_16                             -819907298007
trip_predicted_raw_fare                            -796679905526
driver_created_at_pdt_day                          -767698857914
total_predicted_distance_miles                     -764854671881
claimed_at_pdt_weekday_4 

In [63]:
# score against TRAINING set
model.score(X_train,y_train)

-4.472671736178579e+40

In [64]:
# score against TEST set
model.score(X_test,y_test)

-4.429291409711066e+40

In [65]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [66]:
type(model_y_test_pred)

numpy.ndarray

In [67]:
model_y_test_pred[:10]

array([-7.59970309e+22, -1.00777534e+23,  1.02301252e+23,  9.83383407e+22,
        4.79019170e+21,  1.40094121e+21,  3.84895736e+22,  5.17659215e+21,
       -2.14057266e+22,  1.86812379e+23])

In [68]:
pd.Series(model_y_test_pred).std()

1.071781534330665e+23

In [69]:
pd.Series(model_y_test_pred).corr(y_test)

-0.013697709464620149

In [70]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

-43770976965667737848075654960781358792704.000 1796885431187607126016.00 11623670110131382012713023795317834822881116160 -44292914097110661853370241000401620959232.000 80596155433541296979968 59380573630645363802112 989676227177422782464.00


In [71]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [72]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [73]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [74]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 12662]
 [    3 12473]]


In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.50      0.63     21156
          1       0.00      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.39      0.01       148

avg / total       0.71      0.43      0.53     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [76]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[10670     0     0 10486]
 [ 1447     0     0  1492]
 [  455     0     0   437]
 [   90     0     0    58]]
