### Linear regression model V7
with saturated y values

In [2]:
fileprefix='./lateness_PREP_V5_'

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [5]:
df_X.shape

(125675, 87)

In [6]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [7]:
type(df_y)
df_y.shape

(125675, 2)

In [26]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [29]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [30]:
y.shape

(125675,)

In [32]:
df_X.head()

Unnamed: 0  lead_organizer_created_at_pdt_quarter  is_same_day_ride_int  \
0           5                                      3                     0   
1           6                                      3                     0   
2           7                                      3                     0   
3           8                                      3                     0   
4           9                                      3                     0   

   origin_lat  driver_signup_before_org_signup_secs  \
0       34.18                              -69412.0   
1       34.10                              -69815.0   
2       34.13                              -66508.0   
3       34.11                              -69324.0   
4       34.20                              -70895.0   

   claimed_before_trip_start_secs  trip_created_before_trip_start_secs  \
0                        591987.0                             757206.0   
1                        663477.0                            1015521.0   
2                        238086.0                             240018.0   
3                         85741.0                              87078.0   
4                        657826.0                            9686274.0   

   driver_home_lon  scheduled_ends_at_pdt_weekday  trip_template_id  \
0          -118.25                              1               0.0   
1          -118.25                              1            6325.0   
2          -118.25                              2               0.0   
3          -118.25                              3               0.0   
4          -118.25                              0            3719.0   

                ...                trip_est_duration_secs  \
0               ...                                2188.0   
1               ...                                1740.0   
2               ...                                1134.0   
3               ...                                1376.0   
4               ...                                2130.0   

   org_signup_before_trip_created_secs  lead_organizer_created_at_pdt_day  \
0                           18754828.0                                  3   
1                           16683716.0                                  3   
2                           18750712.0                                  3   
3                           17785068.0                                  3   
4                            7921943.0                                  3   

   shuttle_int  destination_location_id  created_at_pdt_weekofyear  \
0            0                  86289.0                          5   
1            0                  86075.0                          2   
2            0                  88361.0                          5   
3            0                  87908.0                          4   
4            0                  89633.0                         40   

   driver_created_at_pdt_day  driver_created_at_pdt_weekday  \
0                        4.0                            0.0   
1                        4.0                            0.0   
2                        4.0                            0.0   
3                        4.0                            0.0   
4                        4.0                            0.0   

   is_repeating_ride_int  total_predicted_distance_miles  
0                      0                            10.0  
1                      1                             5.0  
2                      0                             5.0  
3                      0                             7.0  
4                      1                            13.0  

[5 rows x 87 columns]

In [33]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [34]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [35]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 87)
(25135, 87)
(100540,)
(25135,)


In [36]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [37]:
# fit model
model=model.fit(X_train,y_train)

In [38]:
model.coef_

array([-5.31659131e-06, -6.35594356e+00,  5.94421546e+00,  1.56605126e+02,
       -1.56495913e+05, -2.18291758e+07,  2.32141350e+07,  3.54872908e+00,
       -7.17322631e+11,  2.36292132e-03, -1.92937692e+11, -5.01209714e-01,
        4.94241566e+11, -6.53145144e+01, -7.67426411e+00, -1.01072962e+00,
        6.90072265e+04,  3.01303875e+11,  7.49660314e+00,  4.68454707e+10,
        4.06027902e-01, -1.60780049e+01, -1.74254571e+00, -4.68454707e+10,
        4.36197346e+01,  2.72353159e+11,  1.15952507e+00, -7.76785078e+00,
        2.07716921e-04, -6.78789640e+01,  1.17312383e+01, -8.16046624e+11,
       -2.51794190e+00, -3.37561593e+01,  4.16018757e+11,  5.00414360e+00,
       -1.30976924e+01,  5.54417771e-02, -1.46862575e+01, -2.26780684e+02,
        5.45694427e-02,  2.38631466e+07,  1.61090219e+01,  2.25500317e+01,
        1.04534799e+01, -3.22613451e+05, -1.06234578e+06, -2.98128993e-01,
        3.46441010e-03, -3.68836162e-01,  1.37167134e+01,  2.36442084e+00,
       -1.55486145e+06,  

In [39]:
pd.Series(model.coef_).astype(int)

0                0
1               -6
2                5
3              156
4          -156495
5        -21829175
6         23214134
7                3
8    -717322630987
9                0
10   -192937691789
11               0
12    494241566354
13             -65
14              -7
15              -1
16           69007
17    301303874958
18               7
19     46845470683
20               0
21             -16
22              -1
23    -46845470679
24              43
25    272353159113
26               1
27              -7
28               0
29             -67
          ...     
57              -6
58               0
59             -19
60               0
61   -745520828349
62               0
63               0
64               0
65               1
66              -3
67             913
68               0
69             477
70              28
71             718
72             -35
73   -272353159310
74              -3
75               0
76              10
77             -15
78          

In [40]:
model.intercept_

1115405672864.3857

In [41]:
X_train.std()

Unnamed: 0                                 6.259357e+04
lead_organizer_created_at_pdt_quarter      8.076552e-01
is_same_day_ride_int                       1.590459e-01
origin_lat                                 1.466141e+00
driver_signup_before_org_signup_secs       1.723678e+07
claimed_before_trip_start_secs             2.381955e+05
trip_created_before_trip_start_secs        1.920172e+06
driver_home_lon                            1.696783e+00
scheduled_ends_at_pdt_weekday              1.357137e+00
trip_template_id                           5.735203e+03
scheduled_starts_at_pdt_dayofyear          1.054582e+02
lead_organizer_created_at_pdt_dayofyear    7.665583e+01
scheduled_starts_at_pdt_weekday            1.357037e+00
driver_home_lat                            1.476480e+00
created_at_pdt_day                         8.901218e+00
claimed_at_pdt_weekday                     2.004019e+00
driver_created_at_pdt_dayofyear            8.074870e+01
scheduled_ends_at_pdt_day                  8.724

In [44]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).astype(int)

scheduled_ends_at_pdt_weekday              -528555977171
scheduled_ends_at_pdt_month                 -78450536641
scheduled_starts_at_pdt_weekofyear          -54136953420
scheduled_ends_at_pdt_weekofyear            -49458235799
scheduled_starts_at_pdt_quarter             -40725511262
scheduled_starts_at_pdt_day                 -34533843555
scheduled_starts_at_pdt_dayofyear            -1829517331
driver_created_at_pdt_weekday                     -43872
driver_created_at_pdt_weekofyear                  -42381
coupon_consumed                                     -165
is_affiliate_int                                    -134
claimed_before_trip_start_secs                       -91
driver_created_at_pdt_quarter                        -76
created_at_pdt_month                                 -64
carpool_int                                          -59
driver_home_lat                                      -44
is_repeating_ride_int                                -27
created_at_pdt_quarter         

In [45]:
# score against TRAINING set
model.score(X_train,y_train)

0.04565596937567884

In [46]:
# score against TEST set
model.score(X_test,y_test)

0.04542368295847066

In [47]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [48]:
type(model_y_test_pred)

numpy.ndarray

In [49]:
model_y_test_pred[:10]

array([-371.41821289, -489.8359375 , -510.69287109, -508.4296875 ,
       -507.60327148, -446.30810547, -317.55908203, -409.35473633,
       -490.80517578, -345.51269531])

In [50]:
pd.Series(model_y_test_pred).std()

108.44369004834678

In [51]:
pd.Series(model_y_test_pred).corr(y_test)

-0.011380490878104168

In [62]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.045 8.34 250507 0.045 375 286 4.77


In [63]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [64]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [65]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [66]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25131]
 [    1     4]]


In [67]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.25      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.74      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [68]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21155     1     0     0]
 [ 2938     1     0     0]
 [  890     2     0     0]
 [  148     0     0     0]]
