### Linear regression model V8
with one-hot encoded date features

In [1]:
fileprefix='./lateness_PREP_V6_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 362)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  driver_created_at_pdt_month_3.0  scheduled_ends_at_pdt_month_2  \
0           5                                0                              1   
1           6                                0                              0   
2           7                                0                              1   
3           8                                0                              0   
4           9                                0                              0   

   scheduled_starts_at_pdt_hour  claimed_at_pdt_quarter_4.0  \
0                            16                           0   
1                            16                           0   
2                            16                           0   
3                            16                           0   
4                            14                           0   

   scheduled_ends_at_pdt_weekday_5  created_at_pdt_quarter_4  \
0                                0                         0   
1                                0                         0   
2                                0                         0   
3                                0                         0   
4                                0                         1   

   claimed_at_pdt_hour_18.0  lead_organizer_created_at_pdt_month_8  \
0                         0                                      0   
1                         0                                      0   
2                         0                                      0   
3                         0                                      0   
4                         0                                      0   

   scheduled_starts_at_pdt_hour_22       ...         created_at_pdt_month_4  \
0                                0       ...                              0   
1                                0       ...                              0   
2                                0       ...                              0   
3                                0       ...                              0   
4                                0       ...                              0   

   created_at_pdt_weekday_0  driver_created_at_pdt_month_11.0  \
0                         0                                 0   
1                         0                                 0   
2                         0                                 0   
3                         0                                 0   
4                         1                                 0   

   driver_created_at_pdt_weekday_2.0  scheduled_ends_at_pdt_month_9  \
0                                  0                              0   
1                                  0                              0   
2                                  0                              0   
3                                  0                              0   
4                                  0                              0   

   scheduled_ends_at_pdt_hour_20  scheduled_ends_at_pdt_month_3  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              0                              0   

   lead_organizer_created_at_pdt_hour_7  lead_organizer_created_at_pdt_hour_4  \
0                                     0                                     0   
1                                     0                                     0   
2                                     0                                     0   
3                                     0                                     0   
4                                     0                                     0   

   destination_lon  
0          -118.23  
1          -118.24  
2          -118.11  
3          -118.28  
4          -118.38  

[5 rows x 362 columns

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 362)
(25135, 362)
(100540,)
(25135,)


In [14]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
model.coef_

array([-9.10204597e-06, -1.88107289e+14, -1.12493766e+15, -4.93923353e+13,
        2.54552552e+14, -1.75592777e+15, -3.50433601e+14,  4.55931167e+14,
        3.48924693e+14,  4.24362294e+14, -2.77609609e+14,  8.89064102e+14,
        5.78187963e+14, -3.62495730e+15,  3.04783346e+14,  1.15256510e+05,
        2.96509412e+12,  5.06030082e-02,  1.26541585e+14, -1.37692245e+15,
       -1.10629728e+15,  4.02316277e+14, -1.04543654e-02, -1.17126548e+15,
        1.43985952e+16, -4.99694531e+14, -1.51831190e+14, -2.97518770e+01,
        2.81612143e+14, -4.51543632e-03, -3.30960167e+13,  1.26850040e+01,
        2.53668295e+12, -7.62286087e+04,  5.37435698e+14, -6.09357415e+14,
       -1.70877744e+14,  1.40583588e+15,  8.78434784e+14,  2.78910553e+14,
       -3.40451378e+14,  1.06081486e+15,  4.80423705e-02, -4.20163141e+14,
       -2.77577982e+14, -2.53786466e+01, -2.79372799e+15, -3.29126831e+00,
       -3.45009382e+15,  5.77553808e+14, -7.99926272e+13, -1.51359712e+15,
        1.67883483e+06,  

In [17]:
pd.Series(model.coef_).astype(int)

0                      0
1       -188107288802910
2      -1124937662046740
3        -49392335289811
4        254552552407957
5      -1755927766463711
6       -350433601118605
7        455931167335538
8        348924692778264
9        424362293749046
10      -277609608664414
11       889064102385292
12       578187963335539
13     -3624957298350644
14       304783346144703
15                115256
16         2965094121981
17                     0
18       126541584520082
19     -1376922450409474
20     -1106297282208050
21       402316276943412
22                     0
23     -1171265483974046
24     14398595191657266
25      -499694530646569
26      -151831189552965
27                   -29
28       281612143237910
29                     0
             ...        
332      -86937551791413
333                  -69
334      -69561059148661
335      416703602697836
336      235882434933064
337      211417575335555
338     -109600735373248
339                   -1
340      924154366201346


In [18]:
model.intercept_

8546598178314728.0

In [19]:
X_train.std()

Unnamed: 0                                 62593.572542
driver_created_at_pdt_month_3.0                0.229514
scheduled_ends_at_pdt_month_2                  0.264999
scheduled_starts_at_pdt_hour                   3.766047
claimed_at_pdt_quarter_4.0                     0.456950
scheduled_ends_at_pdt_weekday_5                0.067194
created_at_pdt_quarter_4                       0.443363
claimed_at_pdt_hour_18.0                       0.221303
lead_organizer_created_at_pdt_month_8          0.383424
scheduled_starts_at_pdt_hour_22                0.036619
claimed_at_pdt_hour_0.0                        0.244425
driver_created_at_pdt_hour_18.0                0.056415
claimed_at_pdt_hour_21.0                       0.187784
scheduled_starts_at_pdt_weekday_4              0.364665
lead_organizer_created_at_pdt_hour_19          0.403735
lead_organizer_created_at_pdt_day              9.349237
driver_created_at_pdt_dayofyear               80.748703
driver_previous_completed_trips              342

In [29]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int)

scheduled_ends_at_pdt_hour_3              -6861521005573226496
scheduled_starts_at_pdt_hour_0             -773548428394554880
scheduled_ends_at_pdt_weekday_6             -91474089073338544
driver_created_at_pdt_hour_4.0              -64343640216620280
driver_created_at_pdt_hour_7.0              -38737135758520784
scheduled_ends_at_pdt_weekday_5             -26132359193392896
driver_created_at_pdt_weekday_6.0           -25110469997652340
scheduled_starts_at_pdt_hour_4              -22740803065577440
scheduled_ends_at_pdt_hour_23               -15779532208189100
scheduled_starts_at_pdt_weekday_5           -14916724175146500
lead_organizer_created_at_pdt_month_2       -14073519584188760
scheduled_ends_at_pdt_hour_4                -13389975951927816
lead_organizer_created_at_pdt_month_1       -11643750708165582
lead_organizer_created_at_pdt_month_3       -11370750294460346
scheduled_starts_at_pdt_hour_5              -11137187281994490
driver_created_at_pdt_quarter_4.0           -1086227574

In [30]:
# score against TRAINING set
model.score(X_train,y_train)

0.06459012670589692

In [31]:
# score against TEST set
model.score(X_test,y_test)

-7.02460277334559e+22

In [32]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [33]:
type(model_y_test_pred)

numpy.ndarray

In [34]:
model_y_test_pred[:10]

array([-276., -388., -549., -601., -499., -420., -319., -448., -502.,
       -388.])

In [35]:
pd.Series(model_y_test_pred).std()

135773619666787.58

In [36]:
pd.Series(model_y_test_pred).corr(y_test)

0.0010796661030326987

In [37]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

-70243232983993657851904.000 2262893661113.65 18434475797429976565641379840 -70246027733455897362432.000 856398605935 281 4.68


In [38]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [39]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [40]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [41]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25113]
 [    1    21]
 [    3     1]]


In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.10      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.72      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [43]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21142    13     0     1]
 [ 2937     2     0     0]
 [  887     5     0     0]
 [  147     1     0     0]]
