### Linear regression model V11
added misc one-hot encoded features driver_gender, platform, metro, region

In [1]:
fileprefix='./lateness_PREP_V9_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 214)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  scheduled_starts_at_pdt_quarter_2  \
0           5                                  0   
1           6                                  0   
2           7                                  0   
3           8                                  0   
4           9                                  0   

   scheduled_starts_at_pdt_month_4  scheduled_starts_at_pdt_month_7  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   claimed_at_pdt_hour_11  origin_analysis_metro_name_Default (Unassigned)  \
0                       0                                                0   
1                       0                                                0   
2                       0                                                0   
3                       0                                                0   
4                       0                                                0   

   claimed_at_pdt_weekday_1  lead_organizer_id  \
0                         1              81281   
1                         1              80068   
2                         0              87802   
3                         0              81561   
4                         0              76793   

   lead_organizer_created_at_pdt_hour  origin_location_id  \
0                                  19             82879.0   
1                                  19             83958.0   
2                                  20             84580.0   
3                                  20             87880.0   
4                                  19             92149.0   

                    ...                     scheduled_starts_at_pdt_weekday_2  \
0                   ...                                                     0   
1                   ...                                                     0   
2                   ...                                                     1   
3                   ...                                                     0   
4                   ...                                                     0   

   scheduled_starts_at_pdt_month_3  scheduled_starts_at_pdt_month_6  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   claimed_at_pdt_hour_2      id  scheduled_starts_at_pdt_hour_10  \
0                      0  338150                                0   
1                      0  310958                                0   
2                      0  338135                                0   
3                      0  324615                                0   
4                      0  247127                                0   

   claimed_at_pdt_month_4  scheduled_ends_at_pdt_hour  organizers_count  \
0                       0                          16               1.0   
1                       0                          16               1.0   
2                       0                          16               1.0   
3                       0                          16               1.0   
4                       0                          15               1.0   

   origin_region_name_Orange County - West  
0                                        0  
1                                        0  
2                                        0  
3                                        0  
4                                        0  

[5 rows x 214 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 214)
(25135, 214)
(100540,)
(25135,)


In [14]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
model.coef_

array([-1.01871686e-05,  5.30369822e+14, -1.03097829e+15, -2.87368236e+14,
       -1.10083611e+15, -8.91482252e+16, -3.73765259e+14,  3.47497369e-03,
        3.98778200e-01,  1.06611593e-04, -1.52018379e+01, -9.00684093e+14,
        4.77309113e+14, -1.22645042e+15, -1.98497717e+14, -6.22701999e+14,
       -1.30098814e+15,  4.01302941e+00, -6.16898129e+16, -9.58973514e+14,
       -6.22701999e+13, -2.63779528e+01, -2.10159622e+15,  1.34733135e+11,
        2.48313750e+00,  6.01849513e+14,  3.48015658e+01,  1.30072951e+08,
       -6.60230573e+00, -8.39101825e+14,  1.21977775e-03, -6.54214861e+12,
        4.32381334e-01,  3.09860054e+07, -9.90869456e+07, -1.45665510e+01,
       -7.79165980e+14, -1.31858858e+15, -1.50114016e+15, -6.90961410e+12,
       -5.60431799e+14,  1.00076010e+14,  9.12350402e+02, -1.79807534e+14,
       -1.25865274e+15, -7.00532073e+14, -1.13878105e+15, -1.19531532e+15,
       -1.44011976e+14, -1.96264458e+13, -9.92488584e+13, -9.06644916e+13,
        3.28113572e+01, -

In [17]:
pd.Series(model.coef_).astype(int)

0                      0
1        530369822124746
2      -1030978288676129
3       -287368235557604
4      -1100836114267292
5     -89148225152143520
6       -373765258844129
7                      0
8                      0
9                      0
10                   -15
11      -900684093491396
12       477309112925265
13     -1226450420380091
14      -198497717149739
15      -622701999378672
16     -1300988135043174
17                     4
18    -61689812938479760
19      -958973513990055
20       -62270199937880
21                   -26
22     -2101596218146646
23          134733134862
24                     2
25       601849512801131
26                    34
27             130072951
28                    -6
29      -839101824741320
             ...        
184    -1801368186982856
185                    2
186    -1164180220442282
187      399530556012866
188     -539422601619402
189      321633613080643
190     -299679223121854
191     -300228031163841
192     -100076010387943


In [18]:
model.intercept_

-399539137114836.0

In [19]:
X_train.std()

Unnamed: 0                                         6.259357e+04
scheduled_starts_at_pdt_quarter_2                  4.191305e-01
scheduled_starts_at_pdt_month_4                    2.495027e-01
scheduled_starts_at_pdt_month_7                    2.181308e-01
claimed_at_pdt_hour_11                             1.985640e-01
origin_analysis_metro_name_Default (Unassigned)    6.307454e-03
claimed_at_pdt_weekday_1                           3.832987e-01
lead_organizer_id                                  2.836254e+04
lead_organizer_created_at_pdt_hour                 4.782270e+00
origin_location_id                                 3.680007e+04
trip_est_duration_secs                             7.517752e+02
claimed_at_pdt_hour_9                              2.171226e-01
origin_region_name_North Bay                       8.977842e-02
origin_region_name_Orange County - South           1.847616e-01
claimed_at_pdt_month_3                             2.793281e-01
origin_region_name_Westside             

In [36]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
# use print to see every feature not just first 20 and last 20
print((model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int).to_string())

origin_analysis_metro_name_Default (Unassigned)   -9223372036854775808
origin_region_name_antelope-valley                 -651573841444286592
scheduled_starts_at_pdt_hour_23                     -77281560373768816
scheduled_starts_at_pdt_hour_3                      -57013450416174136
scheduled_starts_at_pdt_hour_22                     -36008205399018092
scheduled_starts_at_pdt_hour_21                     -20069524985243216
claimed_at_pdt_hour_23                              -18089657016276980
scheduled_starts_at_pdt_hour_20                     -13533939006715420
claimed_at_pdt_hour_22                              -13126053532044140
origin_region_name_Pomona Valley                    -11888911049702508
scheduled_starts_at_pdt_hour_4                      -11732214309986624
claimed_at_pdt_hour_21                              -11191540164066754
claimed_at_pdt_hour_20                              -10103398453444082
origin_region_name_Inland Empire                     -9641608931583952
origin

In [21]:
# score against TRAINING set
model.score(X_train,y_train)

0.054004996011660755

In [22]:
# score against TEST set
model.score(X_test,y_test)

0.05118080348475107

In [23]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([-333.1875, -464.0625, -487.75  , -600.    , -476.75  , -449.0625,
       -302.8125, -420.375 , -527.625 , -357.8125])

In [26]:
pd.Series(model_y_test_pred).std()

118.03918765802274

In [27]:
pd.Series(model_y_test_pred).corr(y_test)

-0.007083311198758798

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.051 8.32 248996 0.051 373 284 4.73


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25123]
 [    1    12]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.17      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.73      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21147     9     0     0]
 [ 2937     2     0     0]
 [  891     1     0     0]
 [  148     0     0     0]]
