### Linear regression model V13
try ridge regression

In [1]:
fileprefix='./lateness_PREP_V10_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 215)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  lead_organizer_created_at_pdt_hour  creator_id  \
0           5                                  19       81281   
1           6                                  19       80068   
2           7                                  20       87802   
3           8                                  20       81561   
4           9                                  19       76793   

   claimed_at_pdt_hour_14  origin_region_name_East Bay South  \
0                       0                                  0   
1                       0                                  0   
2                       0                                  0   
3                       0                                  0   
4                       0                                  0   

   scheduled_starts_at_pdt_month  carpool_int  \
0                              2            0   
1                              1            0   
2                              2            0   
3                              1            0   
4                              1            0   

   scheduled_starts_at_pdt_weekofyear  scheduled_starts_at_pdt_hour_2  \
0                                   7                               0   
1                                   4                               0   
2                                   6                               0   
3                                   4                               0   
4                                   4                               0   

   origin_region_name_Central LA - West    ...      destination_region_id  \
0                                     0    ...                       36.0   
1                                     0    ...                       36.0   
2                                     0    ...                       48.0   
3                                     0    ...                       36.0   
4                                     0    ...                       33.0   

   claimed_at_pdt_hour_6  organizers_count  scheduled_starts_at_pdt_hour_5  \
0                      0               1.0                               0   
1                      0               1.0                               0   
2                      0               1.0                               0   
3                      0               1.0                               0   
4                      0               1.0                               0   

   scheduled_starts_at_pdt_hour_6  origin_region_name_Ventura  \
0                               0                           0   
1                               0                           0   
2                               0                           0   
3                               0                           0   
4                               0                           0   

   lead_organizer_created_at_pdt_month  scheduled_starts_at_pdt_month_2  \
0                                    7                                1   
1                                    7                                0   
2                                    7                                1   
3                                    7                                0   
4                                    7                                0   

   origin_region_name_Pomona Valley  driver_id  
0                                 0    62969.0  
1                                 0    62969.0  
2                                 0    62969.0  
3                                 0    62969.0  
4                                 0    62969.0  

[5 rows x 215 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 215)
(25135, 215)
(100540,)
(25135,)


In [35]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.Ridge(alpha = .75)

In [36]:
# fit model
model=model.fit(X_train,y_train)

In [37]:
model.coef_

array([-1.03720295e-05,  5.30011854e-01, -3.30934856e-03,  9.33439771e+00,
       -1.14861725e+02, -3.55243391e+00, -4.49986202e+00, -4.86750467e-01,
       -5.94821165e-04, -1.82789965e+01, -1.52047477e+01,  3.24008183e+00,
        2.92001422e+01, -1.54566384e+01,  4.78492489e+02, -1.74216888e+02,
        3.05324435e+01,  8.88690147e+01, -1.11183823e+00,  4.77214586e+01,
        3.14378560e-01, -2.27659168e+00, -2.12295989e+01, -2.00801286e+01,
       -8.27591985e+01, -9.51579969e+01, -1.77632113e+01,  1.03828581e+00,
       -1.77626821e+02, -1.15939262e+01,  1.54830053e+02, -1.25143584e+01,
        9.08053143e+01,  1.98512583e+01, -1.35981275e+01,  1.72320284e-01,
       -4.71411275e+01,  6.48278854e+00, -1.25143222e+01, -2.37270175e+01,
        1.27170003e+01,  1.43801269e+02, -3.51232305e+01, -4.88171162e-01,
        1.53080716e-03, -8.87106893e-05,  9.65198569e+00,  8.01542144e+00,
       -2.14833909e+01,  3.64308349e+01,  1.81261950e+02, -3.87350962e+00,
        1.60496890e+00,  

In [38]:
pd.Series(model.coef_).astype(int)

0        0
1        0
2        0
3        9
4     -114
5       -3
6       -4
7        0
8        0
9      -18
10     -15
11       3
12      29
13     -15
14     478
15    -174
16      30
17      88
18      -1
19      47
20       0
21      -2
22     -21
23     -20
24     -82
25     -95
26     -17
27       1
28    -177
29     -11
      ... 
185    -17
186    -10
187     23
188    -43
189      0
190      3
191   -110
192     32
193    -38
194    -14
195     -4
196      0
197    177
198    -41
199    191
200      0
201   -177
202    -31
203     15
204      0
205      0
206     -1
207     -3
208     21
209     46
210    -34
211    -68
212     10
213   -148
214      0
Length: 215, dtype: int64

In [39]:
model.intercept_

-6494.421409884282

In [40]:
X_train.std()

Unnamed: 0                               6.259357e+04
lead_organizer_created_at_pdt_hour       4.782270e+00
creator_id                               2.835762e+04
claimed_at_pdt_hour_14                   2.110560e-01
origin_region_name_East Bay South        1.291162e-01
scheduled_starts_at_pdt_month            3.471655e+00
carpool_int                              1.312920e-01
scheduled_starts_at_pdt_weekofyear       1.507374e+01
scheduled_starts_at_pdt_hour_2           0.000000e+00
origin_region_name_Central LA - West     2.467008e-01
claimed_at_pdt_weekday_5                 2.344145e-01
lead_organizer_created_at_pdt_quarter    8.076552e-01
claimed_at_pdt_month_3                   2.793281e-01
claimed_at_pdt_hour_8                    2.012094e-01
total_predicted_duration                 1.252958e+01
scheduled_starts_at_pdt_weekday          1.357037e+00
claimed_at_pdt_month_10                  3.337243e-01
lead_organizer_platform_web              7.853678e-02
is_same_day_ride_int        

In [41]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
# use print to see every feature not just first 20 and last 20
print((model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int).to_string())

scheduled_starts_at_pdt_hour_3                    -35145
origin_region_name_Pomona Valley                   -5679
origin_region_name_East Contra Costa               -5677
origin_region_name_antelope-valley                 -2439
scheduled_starts_at_pdt_hour_4                     -2139
origin_region_name_North Bay                       -1059
scheduled_starts_at_pdt_weekday_6                  -1044
driver_gender_male                                  -935
origin_region_name_East Bay North                   -898
origin_region_name_East Bay South                   -889
origin_region_name_Inland Empire                    -821
scheduled_starts_at_pdt_hour_21                     -760
claimed_at_pdt_hour_4                               -632
origin_region_name_Southeast LA                     -630
origin_region_name_San Francisco                    -524
origin_region_name_Ventura                          -470
claimed_at_pdt_hour_3                               -462
origin_region_name_South LA    

In [42]:
# score against TRAINING set
model.score(X_train,y_train)

0.05481997076111856

In [43]:
# score against TEST set
model.score(X_test,y_test)

0.05210928495282685

In [44]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [45]:
type(model_y_test_pred)

numpy.ndarray

In [46]:
model_y_test_pred[:10]

array([-337.07703602, -456.81456881, -483.54349511, -582.88394794,
       -486.08087179, -440.92981934, -291.39203378, -455.45163583,
       -530.09586564, -346.35708708])

In [47]:
pd.Series(model_y_test_pred).std()

118.05080187748986

In [48]:
pd.Series(model_y_test_pred).corr(y_test)

-0.006922137026179084

In [49]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.052 8.31 248752 0.052 373 284 4.73


In [50]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [51]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [52]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [53]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25122]
 [    1    13]]


In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.15      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.73      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [55]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21146    10     0     0]
 [ 2937     2     0     0]
 [  891     1     0     0]
 [  148     0     0     0]]
