### Linear regression model V9
with REDUCED number of one-hot encoded date features

In [1]:
fileprefix='./lateness_PREP_V7_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 216)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  claimed_at_pdt_month_2.0  \
0           5                         1   
1           6                         0   
2           7                         1   
3           8                         0   
4           9                         0   

   lead_organizer_created_at_pdt_quarter  scheduled_starts_at_pdt_month_6  \
0                                      3                                0   
1                                      3                                0   
2                                      3                                0   
3                                      3                                0   
4                                      3                                0   

   scheduled_starts_at_pdt_month_6.1  scheduled_starts_at_pdt_hour_19  \
0                                  0                                0   
1                                  0                                0   
2                                  0                                0   
3                                  0                                0   
4                                  0                                0   

   scheduled_starts_at_pdt_hour_19.1  claimed_at_pdt_month_11.0  \
0                                  0                          0   
1                                  0                          0   
2                                  0                          0   
3                                  0                          0   
4                                  0                          0   

   claimed_at_pdt_day  destination_lat                 ...                   \
0                 7.0            34.18                 ...                    
1                17.0            34.10                 ...                    
2                 5.0            34.16                 ...                    
3                25.0            34.17                 ...                    
4                16.0            34.12                 ...                    

   scheduled_starts_at_pdt_hour_3  scheduled_starts_at_pdt_hour_3.1  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 0   
3                               0                                 0   
4                               0                                 0   

   claimed_at_pdt_hour_19.0  scheduled_starts_at_pdt_quarter_4  \
0                         1                                  0   
1                         0                                  0   
2                         0                                  0   
3                         0                                  0   
4                         0                                  0   

   scheduled_starts_at_pdt_quarter_4.1  claimed_at_pdt_month_10.0  \
0                                    0                          0   
1                                    0                          0   
2                                    0                          0   
3                                    0                          0   
4                                    0                          0   

   scheduled_starts_at_pdt_month  org_signup_before_trip_created_secs  \
0                              2                           18754828.0   
1                              1                           16683716.0   
2                              2                           18750712.0   
3                              1                           17785068.0   
4                              1                            7921943.0   

   scheduled_starts_at_pdt_weekday_6  scheduled_starts_at_pdt_weekday_6.1  
0                                  0                                    0  
1                                  0                                    0  
2                                  0                      

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 216)
(25135, 216)
(100540,)
(25135,)


In [14]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
model.coef_

array([-6.98006406e-06,  1.17765119e+14, -4.56598300e+00,  1.50402871e+14,
        6.82306122e+14,  1.01212869e+15, -2.29846638e+15,  1.71056279e+14,
        1.24118905e+05,  1.24020907e+01, -6.86758902e+00,  2.38070911e+14,
       -2.57264831e+14,  2.76106908e+14,  2.30130737e+01, -1.55897492e+01,
       -2.13781618e+14, -9.38751568e+14, -1.40812735e+15,  4.64270695e-01,
       -6.95498395e+14, -3.20031363e+14, -1.12650188e+15,  6.41344854e+14,
       -1.34492372e+01, -8.57305152e+14, -8.53023401e+13, -8.92037317e+14,
        2.25107397e+14, -8.44876412e+14, -1.01698476e+14, -4.40375323e+14,
        4.79817832e+08, -1.22037704e+15,  2.35530237e+14, -1.45392636e+15,
        6.40815666e+14, -6.10511124e+14, -7.52608736e+13,  3.65344262e-03,
       -1.68975282e+15,  2.11208665e+01,  2.24915026e+01, -1.44531880e+16,
        1.41823801e+16, -6.57126098e+14, -4.31056110e+00,  4.18026820e-02,
       -3.11510358e+12,  1.79800787e+13,  1.16022064e+00, -1.19156041e+00,
       -2.22169237e+15,  

In [17]:
pd.Series(model.coef_).astype(int)

0                     0
1       117765118679326
2                    -4
3       150402870770411
4       682306121614365
5      1012128688782244
6     -2298466382023240
7       171056279370881
8                124118
9                    12
10                   -6
11      238070911406720
12     -257264830866386
13      276106907653522
14                   23
15                  -15
16     -213781617931338
17     -938751568491299
18    -1408127352736958
19                    0
20     -695498395106504
21     -320031362715329
22    -1126501882189583
23      641344853794023
24                  -13
25     -857305152028123
26      -85302340071230
27     -892037317424268
28      225107396636210
29     -844876411642155
             ...       
186     -44134821266552
187    -226902078032182
188                  -7
189   -1877503136982645
190      93875156849145
191     208342992811791
192                  10
193   -1545666338972348
194     190481842478803
195    -561796135179843
196    -58913759

In [18]:
model.intercept_

-139853992874615.69

In [19]:
X_train.std()

Unnamed: 0                               6.259357e+04
claimed_at_pdt_month_2.0                 2.673082e-01
lead_organizer_created_at_pdt_quarter    8.076552e-01
scheduled_starts_at_pdt_month_6          2.505018e-01
scheduled_starts_at_pdt_month_6.1        2.505018e-01
scheduled_starts_at_pdt_hour_19          1.239060e-01
scheduled_starts_at_pdt_hour_19.1        1.239060e-01
claimed_at_pdt_month_11.0                3.060840e-01
claimed_at_pdt_day                       8.788468e+00
destination_lat                          1.466265e+00
created_at_pdt_day                       8.901218e+00
claimed_at_pdt_quarter                   1.146429e+00
scheduled_starts_at_pdt_month_2          2.649988e-01
scheduled_starts_at_pdt_month_2.1        2.649988e-01
shuttle_int                              9.784898e-02
carpool_int                              1.312920e-01
claimed_at_pdt_weekday                   2.004019e+00
claimed_at_pdt_hour_10.0                 1.934523e-01
claimed_at_pdt_hour_15.0    

In [20]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int)

scheduled_starts_at_pdt_hour_4        -707289187004427392
scheduled_starts_at_pdt_hour_23        -68733792169853384
scheduled_starts_at_pdt_hour_20        -41419596993651440
scheduled_starts_at_pdt_hour_3.1       -32200461374739920
scheduled_starts_at_pdt_hour_3         -32200461374719628
scheduled_starts_at_pdt_hour_22.1      -29886369882305264
scheduled_starts_at_pdt_hour_21        -25072429993960736
scheduled_starts_at_pdt_weekday_5      -23078869593689108
scheduled_starts_at_pdt_hour_11        -19474324563416432
scheduled_starts_at_pdt_hour_23.1      -18561464708359304
scheduled_starts_at_pdt_hour_19.1      -18550075206673488
claimed_at_pdt_hour_23.0               -16968795849946328
scheduled_starts_at_pdt_weekday_6      -16802398026197068
scheduled_starts_at_pdt_weekday_6.1    -16802398026196938
claimed_at_pdt_hour_22.0               -12312744376541214
scheduled_starts_at_pdt_hour_22        -10787569991943338
claimed_at_pdt_hour_21.0               -10498096239173984
claimed_at_pdt

In [21]:
# score against TRAINING set
model.score(X_train,y_train)

0.048872336347142165

In [22]:
# score against TEST set
model.score(X_test,y_test)

0.04759446309068228

In [23]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([-341.6875  , -482.09375 , -485.78125 , -553.875   , -527.59375 ,
       -444.203125, -321.015625, -452.25    , -535.265625, -360.140625])

In [26]:
pd.Series(model_y_test_pred).std()

112.24184598315682

In [27]:
pd.Series(model_y_test_pred).corr(y_test)

-0.01268815451684004

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.048 8.33 249937 0.048 374 285 4.75


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25129]
 [    1     6]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.00      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.71      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21152     4     0     0]
 [ 2939     0     0     0]
 [  890     2     0     0]
 [  148     0     0     0]]
