### Linear regression model V10
fixed bug with non-integer one-hot encoded date features

In [1]:
fileprefix='./lateness_PREP_V8_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 173)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  scheduled_ends_at_pdt_weekday  scheduled_starts_at_pdt_month_7  \
0           5                              1                                0   
1           6                              1                                0   
2           7                              2                                0   
3           8                              3                                0   
4           9                              0                                0   

   claimed_at_pdt_weekday_3  trip_predicted_raw_fare  \
0                         0                    32.50   
1                         0                    23.09   
2                         0                    17.81   
3                         0                    22.56   
4                         0                    36.19   

   scheduled_starts_at_pdt_hour_7  total_predicted_distance_miles  \
0                               0                            10.0   
1                               0                             5.0   
2                               0                             5.0   
3                               0                             7.0   
4                               0                            13.0   

   driver_signup_before_trip_created_secs  scheduled_starts_at_pdt_hour_2  \
0                              18685416.0                               0   
1                              16613901.0                               0   
2                              18684204.0                               0   
3                              17715744.0                               0   
4                               7851048.0                               0   

   scheduled_starts_at_pdt_day          ...            \
0                           14          ...             
1                           24          ...             
2                            8          ...             
3                           26          ...             
4                           23          ...             

   claimed_at_pdt_weekofyear  lead_organizer_created_at_pdt_hour  \
0                          6                                  19   
1                          3                                  19   
2                          5                                  20   
3                          4                                  20   
4                          3                                  19   

   scheduled_starts_at_pdt_hour_10  claimed_at_pdt_hour_20  \
0                                0                       0   
1                                0                       0   
2                                0                       0   
3                                0                       0   
4                                0                       0   

   claimed_at_pdt_hour_12  destination_region_id  \
0                       0                   36.0   
1                       0                   36.0   
2                       0                   48.0   
3                       0                   36.0   
4                       0                   33.0   

   scheduled_starts_at_pdt_month_10  total_predicted_duration  \
0                                 0                     36.47   
1                                 0                     29.00   
2                                 0                     18.90   
3                                 0                     22.93   
4                                 0                     35.50   

   claimed_at_pdt_quarter_2  claimed_at_pdt_hour_2  
0                         0                      0  
1                         0                      0  
2                         0                      0  
3                         0                      0  
4                         0                      0  

[5 rows x 173 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 173)
(25135, 173)
(100540,)
(25135,)


In [14]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
model.coef_

array([-6.38117582e-06, -1.96573323e+14,  2.80986646e+14,  9.14604671e+13,
       -3.22947844e-01, -1.80172203e+13,  3.75375261e+00, -1.47734009e+07,
       -1.85277459e+16, -1.92595308e+14,  3.09036443e+01,  7.60287557e+00,
        1.11056204e+14, -1.69911472e+01, -1.42908528e+15, -5.65779528e+05,
       -1.01099642e+15, -8.72495149e+00,  1.61481708e+02,  1.00939873e+01,
        3.16206966e+14,  4.29152730e+00, -1.71492987e+04,  6.71841043e+14,
        4.59543826e+13,  6.09736447e+13,  3.70147912e-03, -5.40516610e+13,
       -1.37058306e+14, -1.50154801e+07,  1.60310972e+15,  1.93164159e+15,
        2.34316398e+01, -1.05695080e+15,  6.15680962e+14,  1.86779779e+01,
        1.76429443e+15, -2.16675273e+02, -5.14777724e+13,  2.26506579e+14,
        1.04638162e+13, -1.37863148e+14, -1.02955545e+13,  7.44744829e+02,
       -8.08257366e+04, -6.94215763e+06,  1.95898269e+00,  3.04868224e+13,
       -2.18443488e+12, -4.07492472e+13, -2.29771913e+14, -1.54433317e+13,
       -1.04998851e-02,  

In [17]:
pd.Series(model.coef_).astype(int)

0                      0
1       -196573322776005
2        280986646132845
3         91460467117945
4                      0
5        -18017220338911
6                      3
7              -14773400
8     -18527745924005848
9       -192595307643385
10                    30
11                     7
12       111056203841541
13                   -16
14     -1429085276380031
15               -565779
16     -1010996416790062
17                    -8
18                   161
19                    10
20       316206965530914
21                     4
22                -17149
23       671841042842758
24        45954382581380
25        60973644745304
26                     0
27       -54051661016998
28      -137058305690306
29             -15015480
             ...        
143       48154533038370
144      -38608329297837
145                    0
146      -30486822372646
147                    0
148                    0
149                   42
150     -781224503883246
151             12588017


In [18]:
model.intercept_

-626731765991412.5

In [19]:
X_train.std()

Unnamed: 0                                  6.259357e+04
scheduled_ends_at_pdt_weekday               1.357137e+00
scheduled_starts_at_pdt_month_7             2.181308e-01
claimed_at_pdt_weekday_3                    3.603760e-01
trip_predicted_raw_fare                     1.222204e+01
scheduled_starts_at_pdt_hour_7              3.682657e-01
total_predicted_distance_miles              5.668047e+00
driver_signup_before_trip_created_secs      1.246842e+07
scheduled_starts_at_pdt_hour_2              0.000000e+00
scheduled_starts_at_pdt_day                 8.724887e+00
scheduled_ends_at_pdt_hour                  3.780759e+00
organizers_count                            1.717336e-01
claimed_at_pdt_month_4                      2.604898e-01
driver_created_at_pdt_hour                  2.327039e+00
claimed_at_pdt_quarter_4                    4.569504e-01
driver_created_at_pdt_weekofyear            1.146398e+01
claimed_at_pdt_hour_22                      1.677330e-01
is_same_day_ride_int           

In [20]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int)

claimed_at_pdt_hour_23              -8306676256070094
claimed_at_pdt_hour_22              -6027415396125470
claimed_at_pdt_hour_21              -5139096936224958
claimed_at_pdt_hour_20              -4639427931846646
claimed_at_pdt_hour_18              -3737773889502062
claimed_at_pdt_hour_19              -3693321708411689
claimed_at_pdt_hour_17              -3417030255649621
scheduled_starts_at_pdt_hour_23     -3318784110190134
claimed_at_pdt_hour_15              -3269674979182198
scheduled_starts_at_pdt_quarter_2   -3226785536048879
claimed_at_pdt_quarter_4            -3127440783354361
claimed_at_pdt_hour_14              -3048296813711447
claimed_at_pdt_hour_16              -3045619925065257
claimed_at_pdt_hour_13              -2791071485913993
claimed_at_pdt_hour_11              -2545769468625431
scheduled_starts_at_pdt_hour_3      -2448389142260039
claimed_at_pdt_hour_10              -2375488979411549
claimed_at_pdt_hour_4               -2242711503700317
claimed_at_pdt_hour_3       

In [21]:
# score against TRAINING set
model.score(X_train,y_train)

0.04874752851704512

In [22]:
# score against TEST set
model.score(X_test,y_test)

0.047302177287114285

In [23]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([-342.125, -497.5  , -482.125, -557.125, -530.25 , -438.5  ,
       -325.75 , -451.875, -535.875, -375.625])

In [26]:
pd.Series(model_y_test_pred).std()

111.7414377610852

In [27]:
pd.Series(model_y_test_pred).corr(y_test)

-0.013375503293490383

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.047 8.33 250014 0.047 375 286 4.76


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25130]
 [    1     5]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.20      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.73      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21154     2     0     0]
 [ 2938     1     0     0]
 [  890     2     0     0]
 [  148     0     0     0]]
