### Ensemble Piecewise Linear regression model V16
try random forest regressor with deeper trees

In [1]:
fileprefix='./lateness_PREP_V10_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 215)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  organizer_home_lat  claimed_at_pdt_month_7  \
0           5               34.17                       0   
1           6               34.08                       0   
2           7               34.16                       0   
3           8               34.05                       0   
4           9               34.12                       0   

   claimed_at_pdt_hour_1  driver_created_at_pdt_weekofyear  \
0                      0                                27   
1                      0                                27   
2                      0                                27   
3                      0                                27   
4                      0                                27   

   scheduled_starts_at_pdt_hour_1  scheduled_starts_at_pdt_weekday_4  \
0                               0                                  0   
1                               0                                  0   
2                               0                                  0   
3                               0                                  0   
4                               0                                  0   

   origin_region_name_Malibu  is_same_day_ride_int  is_affiliate_int  \
0                          0                     0                 0   
1                          0                     0                 0   
2                          0                     0                 0   
3                          0                     0                 0   
4                          0                     0                 0   

                  ...                  claimed_at_pdt_quarter  \
0                 ...                                       1   
1                 ...                                       1   
2                 ...                                       1   
3                 ...                                       1   
4                 ...                                       1   

   origin_region_name_Peninsula South  scheduled_starts_at_pdt_month_3  \
0                                   0                                0   
1                                   0                                0   
2                                   0                                0   
3                                   0                                0   
4                                   0                                0   

   claimed_at_pdt_weekday_3  claimed_at_pdt_hour_9  \
0                         0                      0   
1                         0                      0   
2                         0                      0   
3                         0                      0   
4                         0                      0   

   driver_created_at_pdt_hour  scheduled_starts_at_pdt_quarter_4  \
0                          15                                  0   
1                          15                                  0   
2                          15                                  0   
3                          15                                  0   
4                          15                                  0   

   origin_region_name_East Contra Costa  scheduled_starts_at_pdt_month_5  \
0                                     0                                0   
1                                     0                                0   
2                                     0                                0   
3                                     0                                0   
4                                     0                                0   

   lead_organizer_created_at_pdt_hour  
0                                  19  
1                                  19  
2                                  20  
3                                  20  
4                                  19  

[5 rows x 215 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 215)
(25135, 215)
(100540,)
(25135,)


In [14]:
# select a regressor
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(max_depth=4, random_state=808, n_estimators=100)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
print(model.feature_importances_)

[1.12083979e-04 1.02080154e-04 0.00000000e+00 0.00000000e+00
 3.91277898e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 6.41034821e-04 0.00000000e+00
 0.00000000e+00 1.27026333e-04 0.00000000e+00 1.11700504e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.04797408e-03 4.02747538e-04 0.00000000e+00 3.61100061e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 2.44467176e-03 0.00000000e+00 6.06896802e-05
 1.26198227e-04 0.00000000e+00 0.00000000e+00 1.85711162e-04
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.28053534e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.29826121e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.66294523e-04 0.00000000e+00
 0.00000000e+00 1.58730921e-03 1.84298478e-05 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.683588

In [17]:
importances = list(zip(model.feature_importances_, X_train.columns))
importances.sort(reverse=True)
importances

[(0.34210512395180026, 'scheduled_starts_at_pdt_hour'),
 (0.15700488200864898, 'claimed_before_trip_start_secs'),
 (0.12982612144253974, 'scheduled_ends_at_pdt_hour'),
 (0.11170050430987892, 'driver_home_lat'),
 (0.10820354458690712, 'driver_previous_completed_trips'),
 (0.04213593990696024, 'driver_signup_before_trip_start_secs'),
 (0.03611000606833313, 'driver_created_at_pdt_dayofyear'),
 (0.018844804116428047, 'driver_signup_before_trip_claimed_secs'),
 (0.016011651337236473, 'driver_id'),
 (0.003912778977560006, 'driver_created_at_pdt_weekofyear'),
 (0.0030755930956101944, 'total_predicted_duration'),
 (0.0030479740804872273, 'claimed_after_created'),
 (0.0028991903853852184, 'driver_home_lon'),
 (0.0024446717648946405, 'destination_lat'),
 (0.0022243187423367987, 'trip_est_duration_secs'),
 (0.0016927811199605595, 'trip_claimed_after_trip_created'),
 (0.0015873092123953971, 'trip_predicted_raw_fare'),
 (0.0013004414880583878, 'driver_signup_before_trip_created_secs'),
 (0.00128053

In [18]:
# top 10 importances
dict(importances[:10]).values()


dict_values(['scheduled_starts_at_pdt_hour', 'claimed_before_trip_start_secs', 'scheduled_ends_at_pdt_hour', 'driver_home_lat', 'driver_previous_completed_trips', 'driver_signup_before_trip_start_secs', 'driver_created_at_pdt_dayofyear', 'driver_signup_before_trip_claimed_secs', 'driver_id', 'driver_created_at_pdt_weekofyear'])

In [19]:
# number of non-zero features used
len([(i,f) for i, f in importances if i > 0])

69

In [20]:
# number of features wiht importance above 1%
len([(i,f) for i, f in importances if i > 0.01])

9

In [21]:
pd.DataFrame(importances[:10], index=[x for (_,x) in importances[:10] ]).plot(kind = 'bar')

In [22]:
# score against TRAINING set
model.score(X_train,y_train)

0.06234385083806394

In [23]:
# score against TEST set
model.score(X_test,y_test)

0.0645143253595446

In [24]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [25]:
type(model_y_test_pred)

numpy.ndarray

In [26]:
model_y_test_pred[:10]

array([-521.24409292, -412.21301478, -412.21301478, -504.74740038,
       -547.91986042, -416.51627242, -254.86848043, -504.74740038,
       -504.74740038, -412.21301478])

In [27]:
pd.Series(model_y_test_pred).std()

114.2540160572322

In [28]:
pd.Series(model_y_test_pred).corr(y_test)

-0.030868474098493515

In [29]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.065 8.26 245497 0.065 371 280 4.67


In [30]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [31]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [32]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [33]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25067]
 [    1    19]
 [    2    44]
 [    3     5]]


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.26      0.00      0.00      2939
          2       0.25      0.01      0.02       892
          3       0.40      0.01      0.03       148

avg / total       0.75      0.84      0.77     25135



In [35]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21144     4     7     1]
 [ 2920     5    14     0]
 [  875     4    11     2]
 [  128     6    12     2]]
