### Linear regression model V12
added driver had a ride within past hour

In [1]:
fileprefix='./lateness_PREP_V10_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 215)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
df_y.head()

0      1
0  5 -497.0
1  6    5.0
2  7 -313.0
3  8 -296.0
4  9 -166.0

In [8]:
y=df_y[1]
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [9]:
y.shape

(125675,)

In [10]:
df_X.head()

Unnamed: 0  lead_organizer_created_at_pdt_hour  creator_id  \
0           5                                  19       81281   
1           6                                  19       80068   
2           7                                  20       87802   
3           8                                  20       81561   
4           9                                  19       76793   

   claimed_at_pdt_hour_14  origin_region_name_East Bay South  \
0                       0                                  0   
1                       0                                  0   
2                       0                                  0   
3                       0                                  0   
4                       0                                  0   

   scheduled_starts_at_pdt_month  carpool_int  \
0                              2            0   
1                              1            0   
2                              2            0   
3                              1            0   
4                              1            0   

   scheduled_starts_at_pdt_weekofyear  scheduled_starts_at_pdt_hour_2  \
0                                   7                               0   
1                                   4                               0   
2                                   6                               0   
3                                   4                               0   
4                                   4                               0   

   origin_region_name_Central LA - West    ...      destination_region_id  \
0                                     0    ...                       36.0   
1                                     0    ...                       36.0   
2                                     0    ...                       48.0   
3                                     0    ...                       36.0   
4                                     0    ...                       33.0   

   claimed_at_pdt_hour_6  organizers_count  scheduled_starts_at_pdt_hour_5  \
0                      0               1.0                               0   
1                      0               1.0                               0   
2                      0               1.0                               0   
3                      0               1.0                               0   
4                      0               1.0                               0   

   scheduled_starts_at_pdt_hour_6  origin_region_name_Ventura  \
0                               0                           0   
1                               0                           0   
2                               0                           0   
3                               0                           0   
4                               0                           0   

   lead_organizer_created_at_pdt_month  scheduled_starts_at_pdt_month_2  \
0                                    7                                1   
1                                    7                                0   
2                                    7                                1   
3                                    7                                0   
4                                    7                                0   

   origin_region_name_Pomona Valley  driver_id  
0                                 0    62969.0  
1                                 0    62969.0  
2                                 0    62969.0  
3                                 0    62969.0  
4                                 0    62969.0  

[5 rows x 215 columns]

In [11]:
y.describe().round()

count    125675.0
mean       -416.0
std         509.0
min       -1800.0
25%        -657.0
50%        -324.0
75%         -96.0
max        1800.0
Name: 1, dtype: float64

In [12]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [13]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 215)
(25135, 215)
(100540,)
(25135,)


In [14]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [15]:
# fit model
model=model.fit(X_train,y_train)

In [16]:
model.coef_

array([-1.00585466e-05,  4.41788710e-01, -3.41750350e-03, -1.86017948e+14,
       -1.26303649e+14, -3.81112455e+13, -9.55600396e-01, -2.04021079e+13,
       -3.78772529e+16, -3.53377777e+13, -9.31592667e+14,  3.26447254e+00,
       -3.53130832e+13, -1.06295970e+14,  9.76203422e+02, -8.81149708e+13,
       -1.90605440e+14,  9.06842039e+01,  1.03113063e+00, -1.08634761e+14,
       -1.14175576e+01, -2.48308137e+00, -2.19256352e+01,  3.79140401e+14,
       -8.22986671e+01, -5.56280940e+13,  2.84355301e+14,  1.03437660e+00,
        2.52083209e+12,  9.47851003e+13, -1.72014935e+16, -2.35202023e+14,
       -1.62055022e+15, -2.65033333e+14, -4.04549054e+14,  1.22036728e+05,
       -1.76688888e+13,  1.76565452e+13, -8.89667694e+14,  3.26399162e+14,
       -1.32869963e+14, -8.83444442e+13, -2.62142750e+12,  4.49583955e+12,
        2.52212641e+08, -9.25088418e-05, -7.95193283e+14, -5.58955600e+14,
       -2.08261981e+14, -1.60288133e+15, -8.94245346e+12,  1.51452057e+14,
       -2.79026922e+14, -

In [17]:
pd.Series(model.coef_).astype(int)

0                      0
1                      0
2                      0
3       -186017947995876
4       -126303649335140
5        -38111245468321
6                      0
7        -20402107857531
8     -37877252922600496
9        -35337777668254
10      -931592666555448
11                     3
12       -35313083170491
13      -106295970283375
14                   976
15       -88114970840800
16      -190605439969260
17                    90
18                     1
19      -108634760500859
20                   -11
21                    -2
22                   -21
23       379140401017384
24                   -82
25       -55628093998654
26       284355300763037
27                     1
28         2520832089892
29        94785100254339
             ...        
185                  -17
186      211964883940117
187      158960991875840
188      -85528008256834
189                    0
190      176617533400063
191      -64146006192800
192     -702440782067738
193     -318039999014151


In [18]:
model.intercept_

-443472553406620.5

In [19]:
X_train.std()

Unnamed: 0                               6.259357e+04
lead_organizer_created_at_pdt_hour       4.782270e+00
creator_id                               2.835762e+04
claimed_at_pdt_hour_14                   2.110560e-01
origin_region_name_East Bay South        1.291162e-01
scheduled_starts_at_pdt_month            3.471655e+00
carpool_int                              1.312920e-01
scheduled_starts_at_pdt_weekofyear       1.507374e+01
scheduled_starts_at_pdt_hour_2           0.000000e+00
origin_region_name_Central LA - West     2.467008e-01
claimed_at_pdt_weekday_5                 2.344145e-01
lead_organizer_created_at_pdt_quarter    8.076552e-01
claimed_at_pdt_month_3                   2.793281e-01
claimed_at_pdt_hour_8                    2.012094e-01
total_predicted_duration                 1.252958e+01
scheduled_starts_at_pdt_weekday          1.357037e+00
claimed_at_pdt_month_10                  3.337243e-01
lead_organizer_platform_web              7.853678e-02
is_same_day_ride_int        

In [20]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
# use print to see every feature not just first 20 and last 20
print((model.coef_/X_train.std()).sort_values(axis=0).replace([np.inf, -np.inf], np.nan).dropna().astype(int).to_string())

origin_region_name_Default (Unassigned)           -2727169179423537664
origin_region_name_antelope-valley                 -369762287038972864
scheduled_starts_at_pdt_hour_23                     -27570054176955188
scheduled_starts_at_pdt_hour_3                      -20339443318561720
scheduled_starts_at_pdt_hour_22                     -12845860886665568
origin_region_name_Orange County - West             -11008776322857560
origin_region_name_Orange County - North             -8966063542857170
origin_region_name_East Contra Costa                 -8851536908691808
origin_region_name_Orange County - South             -8771031569666359
origin_region_name_Orange County - Central           -7202586331499325
scheduled_starts_at_pdt_hour_21                      -7159766035687088
origin_region_name_Pomona Valley                     -6746849950879226
origin_region_name_Inland Empire                     -5471526237725377
origin_region_name_Southeast LA                      -5231204707585897
schedu

In [21]:
# score against TRAINING set
model.score(X_train,y_train)

0.05486599271597269

In [22]:
# score against TEST set
model.score(X_test,y_test)

0.0516980954670887

In [23]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [24]:
type(model_y_test_pred)

numpy.ndarray

In [25]:
model_y_test_pred[:10]

array([-329.625 , -456.375 , -485.625 , -587.9375, -482.5   , -439.25  ,
       -288.8125, -461.4375, -529.25  , -348.0625])

In [26]:
pd.Series(model_y_test_pred).std()

119.15905405745319

In [27]:
pd.Series(model_y_test_pred).corr(y_test)

-0.008199351057710483

In [28]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from math import sqrt
print ("%.3f %.2f %.0f %.3f %.0f %.0f %.2f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        sqrt(mean_squared_error(y_test, model_y_test_pred))/60, # sqrt of MSE in minutes
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred),
        median_absolute_error(y_test, model_y_test_pred)/60 # MAE in minutes
       ))

0.052 8.31 248860 0.052 373 284 4.72


In [29]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [30]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [31]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [32]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 25119]
 [    1    16]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      1.00      0.91     21156
          1       0.12      0.00      0.00      2939
          2       0.00      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.72      0.84      0.77     25135



/Applications/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[21143    13     0     0]
 [ 2937     2     0     0]
 [  891     1     0     0]
 [  148     0     0     0]]
