# Linear regression model V1

In [1]:
fileprefix='./lateness_PREP_V1_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [5]:
df_X.shape

(125675, 29)

In [21]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [22]:
type(df_y)
df_y.shape

(125675, 2)

In [23]:
y=df_y.iloc[:,1]

In [24]:
type(y)

pandas.core.series.Series

In [25]:
y.shape

(125675,)

In [26]:
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [27]:
df_X.head()

Unnamed: 0  total_predicted_distance_miles  \
0           5                            10.0   
1           6                             5.0   
2           7                             5.0   
3           8                             7.0   
4           9                            13.0   

   lead_organizer_previous_completed_trips  total_predicted_duration  \
0                                        5                     36.47   
1                                       65                     29.00   
2                                       13                     18.90   
3                                       88                     22.93   
4                                       46                     35.50   

   predicted_driver_fare  organizer_home_lat  destination_lat  \
0                  19.63               34.17            34.18   
1                  14.19               34.08            34.10   
2                  14.06               34.16            34.16   
3                  15.59               34.05            34.17   
4                  21.63               34.12            34.12   

   driver_previous_completed_trips  destination_region_id  coupon_consumed  \
0                            663.0                   36.0              0.0   
1                            634.0                   36.0              0.0   
2                            649.0                   48.0              0.0   
3                            637.0                   36.0              0.0   
4                            629.0                   33.0              0.0   

         ...         driver_home_lon  passengers_count  origin_lon  \
0        ...                 -118.25               1.0     -118.35   
1        ...                 -118.25               1.0     -118.31   
2        ...                 -118.25               1.0     -118.16   
3        ...                 -118.25               1.0     -118.24   
4        ...                 -118.25               1.0     -118.51   

   organizer_home_lon  trip_template_id  origin_lat  claimed_after_created  \
0             -118.34               0.0       34.18                2753.65   
1             -118.34            6325.0       34.10                5867.40   
2             -118.11               0.0       34.13                  32.20   
3             -118.22               0.0       34.11                  22.28   
4             -118.38            3719.0       34.20              150534.13   

   destination_lon  driver_home_lat  route_legs_count  
0          -118.23             34.1                 1  
1          -118.24             34.1                 1  
2          -118.11             34.1                 1  
3          -118.28             34.1                 1  
4          -118.38             34.1                 1  

[5 rows x 29 columns]

In [28]:
y.describe().apply(lambda x: '%.0f' % x)

count      125675
mean         -507
std         22763
min      -7862491
25%          -657
50%          -324
75%           -96
max        204537
Name: 1, dtype: object

In [29]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression()

In [30]:
# fit model
model=model.fit(df_X,y)

In [31]:
model.coef_

array([-4.19692549e-04,  4.73702359e+01,  3.58555063e-02,  2.63339714e+01,
       -3.34848890e+01, -6.14720839e+02, -1.81653660e+04,  1.10699545e+00,
        4.50163588e+01, -4.50395352e+01, -3.25283265e-03, -1.05755212e-02,
        3.82179479e-03,  1.01613851e+02,  6.24973085e-04,  2.70389156e-03,
        4.32179718e+01,  4.83540473e-03, -4.99072432e+00, -8.58495030e+03,
        2.49196918e+01,  5.25170576e+03, -1.81905888e+02, -1.62503795e-02,
       -2.45779577e+04, -1.67218925e-03,  2.69593289e+03,  4.33148922e+04,
       -3.21774114e+02])

In [66]:
pd.Series(model.coef_).apply(lambda x: '%.0f' % x)

0         -0
1         47
2          0
3         26
4        -33
5       -615
6     -18165
7          1
8         45
9        -45
10        -0
11        -0
12         0
13       102
14         0
15         0
16        43
17         0
18        -5
19     -8585
20        25
21      5252
22      -182
23        -0
24    -24578
25        -0
26      2696
27     43315
28      -322
dtype: object

In [32]:
model.intercept_

-98281.3634048134

In [59]:
df_X.std()

Unnamed: 0                                 62574.764615
total_predicted_distance_miles                 5.648633
lead_organizer_previous_completed_trips      205.035384
total_predicted_duration                      12.495387
predicted_driver_fare                          5.869914
organizer_home_lat                             3.520902
destination_lat                                1.465935
driver_previous_completed_trips              343.170859
destination_region_id                         14.230953
coupon_consumed                                0.078336
id                                         90386.207317
creator_id                                 28361.473481
driver_id                                  36476.929023
organizers_count                               0.172448
destination_location_id                    36903.795020
origin_location_id                         36848.424811
origin_region_id                              14.245880
lead_organizer_id                          28366

In [76]:
# normalize the linear odel coefficients by the standard deviation to see which features are most important
(model.coef_/df_X.std()).sort_values(axis=0).apply(lambda x: '%.0f' % x)

origin_lat                                 -16767
destination_lat                            -12392
driver_home_lon                             -5090
route_legs_count                            -1156
coupon_consumed                              -575
organizer_home_lat                           -175
organizer_home_lon                            -16
predicted_driver_fare                          -6
trip_predicted_raw_fare                        -0
trip_template_id                               -0
creator_id                                     -0
claimed_after_created                          -0
id                                             -0
Unnamed: 0                                     -0
destination_location_id                         0
origin_location_id                              0
driver_id                                       0
lead_organizer_id                               0
lead_organizer_previous_completed_trips         0
driver_previous_completed_trips                 0


In [38]:
# score against full training set
model.score(df_X,y)

0.32419216823706354

In [39]:
model_y_pred = model.predict(df_X)
model_y_pred.size

125675

In [42]:
type(model_y_pred)

numpy.ndarray

In [45]:
model_y_pred[:10]

array([-3174.54725717,  -236.23555056,   -65.49284239, -1401.42339247,
       -3838.2072563 , -2516.09309354,  -737.29632668, -3505.40605735,
       -3508.77048622, -1339.0324038 ])

In [52]:
pd.Series(model_y_pred).std()

12960.940850901721

In [53]:
pd.Series(model_y_pred).corr(y)

0.5693787563977618

In [82]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
print ("xvs %.3f mse %.0f r2 %.3f mae %.0f medianae %.0f" % 
       (explained_variance_score(y, model_y_pred),
        mean_squared_error(y, model_y_pred), 
        r2_score(y, model_y_pred), 
        mean_absolute_error(y, model_y_pred), 
        median_absolute_error(y, model_y_pred)))

xvs 0.324 mse 350179165 r2 0.324 mae 3015 medianae 1855


In [102]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
##type(y.values)
##numpy.ndarray
##y.head(10)
bins

array([  0., 300., 900.])

In [94]:
np.digitize(y, bins)[:10]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
# materialize y_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_class=np.digitize(y, bins)
unique, counts = np.unique(y_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[     0 105695]
 [     1  14861]
 [     2   4357]
 [     3    762]]


In [104]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_pred_class=np.digitize(model_y_pred, bins)
print(np.asarray(np.unique(model_y_pred_class, return_counts=True)).T)

[[    0 70954]
 [    1  5376]
 [    2 10208]
 [    3 39137]]


In [106]:
from sklearn.metrics import classification_report
print(classification_report(y_class,model_y_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.56      0.67    105695
          1       0.12      0.04      0.06     14861
          2       0.03      0.07      0.04      4357
          3       0.01      0.29      0.01       762

avg / total       0.72      0.48      0.57    125675



In [111]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_class,model_y_pred_class,labels=[0,1,2,3]))

[[59249  4564  8708 33174]
 [ 8681   620  1159  4401]
 [ 2574   156   289  1338]
 [  450    36    52   224]]
