### Linear regression model V6
with 6*7=42 additional date properies

In [1]:
fileprefix='./lateness_PREP_V4_'

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_X=pd.read_csv(fileprefix+'X.csv', sep='\t')

In [4]:
df_X.shape

(125675, 87)

In [5]:
df_y=pd.read_csv(fileprefix+'y.csv', sep='\t', header=None)

In [6]:
type(df_y)
df_y.shape

(125675, 2)

In [7]:
y=df_y.iloc[:,1]

In [9]:
y.shape

(125675,)

In [10]:
y.head()

0   -497.0
1      5.0
2   -313.0
3   -296.0
4   -166.0
Name: 1, dtype: float64

In [11]:
df_X.head()

Unnamed: 0  is_affiliate_int  driver_signup_before_trip_claimed_secs  \
0           5                 0                              18850635.0   
1           6                 0                              16965945.0   
2           7                 0                              18686136.0   
3           8                 0                              17717081.0   
4           9                 0                              16879496.0   

   claimed_at_pdt_weekofyear  trip_predicted_raw_fare  \
0                        6.0                    32.50   
1                        3.0                    23.09   
2                        5.0                    17.81   
3                        4.0                    22.56   
4                        3.0                    36.19   

   driver_created_at_pdt_dayofyear  claimed_after_created  \
0                            186.0                2753.65   
1                            186.0                5867.40   
2                            186.0                  32.20   
3                            186.0                  22.28   
4                            186.0              150534.13   

   created_at_pdt_month  driver_id  destination_region_id         ...          \
0                     2    62969.0                   36.0         ...           
1                     1    62969.0                   36.0         ...           
2                     2    62969.0                   48.0         ...           
3                     1    62969.0                   36.0         ...           
4                    10    62969.0                   33.0         ...           

   organizer_home_lon  origin_location_id  scheduled_starts_at_pdt_weekday  \
0             -118.34             82879.0                                1   
1             -118.34             83958.0                                1   
2             -118.11             84580.0                                2   
3             -118.22             87880.0                                3   
4             -118.38             92149.0                                0   

   coupon_consumed  organizer_home_lat  total_predicted_distance_miles  \
0              0.0               34.17                            10.0   
1              0.0               34.08                             5.0   
2              0.0               34.16                             5.0   
3              0.0               34.05                             7.0   
4              0.0               34.12                            13.0   

   trip_template_id  lead_organizer_created_at_pdt_hour  is_same_day_ride_int  \
0               0.0                                  19                     0   
1            6325.0                                  19                     0   
2               0.0                                  20                     0   
3               0.0                                  20                     0   
4            3719.0                                  19                     0   

   claimed_at_pdt_day  
0                 7.0  
1                17.0  
2                 5.0  
3                25.0  
4                16.0  

[5 rows x 87 columns]

In [12]:
y.describe().round()

count     125675.0
mean        -507.0
std        22763.0
min     -7862491.0
25%         -657.0
50%         -324.0
75%          -96.0
max       204537.0
Name: 1, dtype: float64

In [13]:
# break df_X,y into test and train sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.20, random_state=808)

In [17]:
for i in X_train, X_test, y_train, y_test:
    print(i.shape)

(100540, 87)
(25135, 87)
(100540,)
(25135,)


In [19]:
# select a linear model
import sklearn.linear_model
model=sklearn.linear_model.LinearRegression(normalize=True)

In [20]:
# fit model
model=model.fit(X_train,y_train)

In [21]:
model.coef_

array([-4.48502055e-04, -2.14803827e+01, -2.75582885e+07,  2.16991066e-01,
       -6.37840858e+00, -1.06813335e+05, -4.66268197e-01,  8.18034503e+02,
        2.71269675e-03,  1.75649611e+00, -2.86423781e+01,  1.07384914e+05,
        2.57939387e+01, -3.95573008e+12,  2.32386900e+07,  1.67563753e+13,
       -2.21731439e+00, -8.79555505e+00,  5.56149689e+02,  1.76012066e+01,
       -2.74785628e+01,  4.00039781e-01,  7.19978703e-04,  6.08031763e+02,
       -1.22216968e+07,  8.36130248e+00, -5.83605049e+01,  1.26639702e+01,
        1.86717153e+03,  6.34082917e+01,  1.17573677e-01,  2.04511963e+06,
        1.60090486e+02,  7.51680443e+05,  1.13827522e+01, -2.27344963e-03,
        1.15159438e+02, -1.88828331e+02,  7.75549895e+03, -7.77589278e-04,
        4.25220122e+12,  2.37555933e+12, -2.27407947e+02,  1.38968918e+01,
        8.09618746e+00,  2.26954450e+00,  4.37503360e+06, -3.56467826e+11,
        7.76229746e+02, -1.29242407e+02, -1.00326021e+02,  3.15078791e+01,
        8.40006820e-01,  

In [22]:
pd.Series(model.coef_).astype(int)

0                  0
1                -21
2          -27558288
3                  0
4                 -6
5            -106813
6                  0
7                818
8                  0
9                  1
10               -28
11            107384
12                25
13    -3955730084021
14          23238690
15    16756375322640
16                -2
17                -8
18               556
19                17
20               -27
21                 0
22                 0
23               608
24         -12221696
25                 8
26               -58
27                12
28              1867
29                63
           ...      
57                82
58     2195013432418
59              -114
60     -296471140053
61           9947217
62             -2294
63     1348913470005
64              -132
65         -15336591
66               -57
67                37
68                26
69   -16756375324581
70                64
71    -1348913470810
72                76
73           

In [23]:
model.intercept_

-3264695352127.095

In [24]:
X_train.std()

Unnamed: 0                                 6.259357e+04
is_affiliate_int                           2.673397e-01
driver_signup_before_trip_claimed_secs     1.236846e+07
claimed_at_pdt_weekofyear                  1.507907e+01
trip_predicted_raw_fare                    1.222204e+01
driver_created_at_pdt_dayofyear            8.074870e+01
claimed_after_created                      3.024465e+04
created_at_pdt_month                       3.496608e+00
driver_id                                  3.646652e+04
destination_region_id                      1.422844e+01
driver_home_lon                            1.696783e+00
driver_created_at_pdt_weekday              1.582086e+00
created_at_pdt_day                         8.901218e+00
scheduled_ends_at_pdt_day                  8.724890e+00
driver_signup_before_trip_created_secs     1.246842e+07
scheduled_ends_at_pdt_month                3.471655e+00
created_at_pdt_hour                        4.993326e+00
claimed_at_pdt_hour                        5.783

In [25]:
# normalize the linear model coefficients by the standard deviation to see which features are most important
(model.coef_/X_train.std()).sort_values(axis=0).astype(int)

scheduled_starts_at_pdt_month             -4826625252702
scheduled_starts_at_pdt_weekday           -2652294102294
scheduled_starts_at_pdt_quarter           -1172689482052
scheduled_ends_at_pdt_day                  -453384503322
scheduled_starts_at_pdt_dayofyear            -3380179687
scheduled_ends_at_pdt_dayofyear              -2811266430
driver_created_at_pdt_dayofyear                    -1322
is_same_day_ride_int                                -968
lead_organizer_created_at_pdt_month                 -917
route_legs_count                                    -813
shuttle_int                                         -591
lead_organizer_created_at_pdt_quarter               -163
driver_home_lat                                     -127
driver_created_at_pdt_quarter                       -113
is_affiliate_int                                     -80
destination_lat                                      -77
claimed_before_trip_start_secs                       -51
driver_home_lon                

In [26]:
# score against TRAINING set
model.score(X_train,y_train)

0.9500664062874965

In [27]:
# score against TEST set
model.score(X_test,y_test)

-0.02745112471696065

In [28]:
model_y_test_pred = model.predict(X_test)
model_y_test_pred.size

25135

In [29]:
type(model_y_test_pred)

numpy.ndarray

In [30]:
model_y_test_pred[:10]

array([-253.70507812, -521.0390625 , -713.17724609, -573.08300781,
       -245.01660156, -481.46679688, -655.80322266, -163.90332031,
       -748.57958984, -397.52783203])

In [31]:
pd.Series(model_y_test_pred).std()

287.4663860724478

In [32]:
pd.Series(model_y_test_pred).corr(y_test)

0.014549252903096568

In [33]:
# regression metrics
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
print ("%.3f %.0f %.3f %.0f %.0f" % 
       (explained_variance_score(y_test, model_y_test_pred),
        mean_squared_error(y_test, model_y_test_pred), 
        r2_score(y_test, model_y_test_pred), 
        mean_absolute_error(y_test, model_y_test_pred), 
        median_absolute_error(y_test, model_y_test_pred)))

-0.027 2140842 -0.027 455 335


In [34]:
# make classifications from seconds late target
bins = np.array([0.0, 5*60, 15*60]) # 0 on-time, 1 almost on-time, 2 late, 3 extremely late
bins

array([  0., 300., 900.])

In [35]:
np.digitize(y_test, bins)[:10]

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [36]:
# materialize y_test_class array
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
y_test_class=np.digitize(y_test, bins)
unique, counts = np.unique(y_test_class, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0 21156]
 [    1  2939]
 [    2   892]
 [    3   148]]


In [37]:
# materialize model_y_pred_class
# check to see how many trips are categorized as 0 on-time, 1 almost on-time, 2 late, 3 extremely late
model_y_test_pred_class=np.digitize(model_y_test_pred, bins)
print(np.asarray(np.unique(model_y_test_pred_class, return_counts=True)).T)

[[    0 24241]
 [    1   867]
 [    2    26]
 [    3     1]]


In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class,model_y_test_pred_class))

             precision    recall  f1-score   support

          0       0.84      0.97      0.90     21156
          1       0.14      0.04      0.06      2939
          2       0.04      0.00      0.00       892
          3       0.00      0.00      0.00       148

avg / total       0.73      0.82      0.77     25135



In [39]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_class,model_y_test_pred_class,labels=[0,1,2,3]))

[[20437   700    19     0]
 [ 2817   119     3     0]
 [  851    39     1     1]
 [  136     9     3     0]]
